local function GET_TEXT(msg)
if chat_type == 'super' then 
if IRAQBOT:get(IRAQ_ID.."skrafa:name" .. msg.chat_id_ .. "" .. msg.sender_user_id_) then   
if text and text:match("^الغاء$") then 
IRAQ_sendMsg(msg.chat_id_, msg.id_, 1, "*💥¦* تم الغاء امر الزخرفه ✔", 1, "md")
IRAQBOT:del(IRAQ_ID.."skrafa:name" .. msg.chat_id_ .. "" .. msg.sender_user_id_)     
return false
end
if text then
if utf8.len(text) > 20 then
IRAQ_sendMsg(msg.chat_id_, msg.id_, 1,'*📮¦ لا يمكن زخرفة اكثر من 20 حرف *', 1, 'md') 
IRAQBOT:del(IRAQ_ID.."skrafa:name" .. msg.chat_id_ .. "" .. msg.sender_user_id_)     
return false
end
local zhrf1 = text:gsub('ض', 'ضِٰـِۢ')
zhrf1 = zhrf1:gsub('ص', 'صِٰـِۢ')
zhrf1 = zhrf1:gsub('ث', 'ثِٰـِۢ')
zhrf1 = zhrf1:gsub('ق', 'قِٰـِۢ')
zhrf1 = zhrf1:gsub('ف', 'فِٰ͒ـِۢ')
zhrf1 = zhrf1:gsub('غ', 'غِٰـِۢ')
zhrf1 = zhrf1:gsub('ع', 'عِٰـِۢ')
zhrf1 = zhrf1:gsub('خ', 'خِٰ̐ـِۢ')
zhrf1 = zhrf1:gsub('ح', 'حِٰـِۢ')
zhrf1 = zhrf1:gsub('ج', 'جِٰـِۢ')
zhrf1 = zhrf1:gsub('ش', 'شِٰـِۢ')
zhrf1 = zhrf1:gsub('س', 'سِٰـِۢ')
zhrf1 = zhrf1:gsub('ي', 'يِٰـِۢ')
zhrf1 = zhrf1:gsub('ب', 'بِٰـِۢ')
zhrf1 = zhrf1:gsub('ل', 'لِٰـِۢ')
zhrf1 = zhrf1:gsub('ا', 'آ')
zhrf1 = zhrf1:gsub('ت', 'تِٰـِۢ')
zhrf1 = zhrf1:gsub('ن', 'نِٰـِۢ')
zhrf1 = zhrf1:gsub('م', 'مِٰـِۢ')
zhrf1 = zhrf1:gsub('ك', 'ڪِٰـِۢ')
zhrf1 = zhrf1:gsub('ط', 'طِٰـِۢ')
zhrf1 = zhrf1:gsub('ظ', 'ظِٰـِۢ')
zhrf1 = zhrf1:gsub('ء', 'ء')
zhrf1 = zhrf1:gsub('ؤ', 'ؤ')
zhrf1 = zhrf1:gsub('ر', 'ر')
zhrf1 = zhrf1:gsub('ى', 'ى')
zhrf1 = zhrf1:gsub('ز', 'ز')
zhrf1 = zhrf1:gsub('و', 'ﯛ̲୭')
zhrf1 = zhrf1:gsub("ه", "ۿۿہ")
zhrf1 = zhrf1:gsub('a','Ꭿ')
zhrf1 = zhrf1:gsub('A','Ꭿ')
zhrf1 = zhrf1:gsub("b","Ᏸ")
zhrf1 = zhrf1:gsub("B","Ᏸ")
zhrf1 = zhrf1:gsub("c","Ꮸ")
zhrf1 = zhrf1:gsub("C","Ꮸ")
zhrf1 = zhrf1:gsub("d","Ꮷ")
zhrf1 = zhrf1:gsub("D","Ꮷ")
zhrf1 = zhrf1:gsub("e","Ꮛ")
zhrf1 = zhrf1:gsub("E","Ꮛ")
zhrf1 = zhrf1:gsub("f","Ꭶ")
zhrf1 = zhrf1:gsub("F","Ꭶ")
zhrf1 = zhrf1:gsub("g","Ᏻ")
zhrf1 = zhrf1:gsub("G","Ᏻ")
zhrf1 = zhrf1:gsub("h","Ᏺ")
zhrf1 = zhrf1:gsub("H","Ᏺ")
zhrf1 = zhrf1:gsub("i","Ꭸ")
zhrf1 = zhrf1:gsub("I","Ꭸ")
zhrf1 = zhrf1:gsub("j","Ꮰ")
zhrf1 = zhrf1:gsub("J","Ꮰ")
zhrf1 = zhrf1:gsub("k","Ꮵ")
zhrf1 = zhrf1:gsub("K","Ꮵ")
zhrf1 = zhrf1:gsub("l","Ꮭ")
zhrf1 = zhrf1:gsub("L","Ꮭ")
zhrf1 = zhrf1:gsub("m","ᗰ")
zhrf1 = zhrf1:gsub("M","ᗰ")
zhrf1 = zhrf1:gsub("n","Ꮑ")
zhrf1 = zhrf1:gsub("N","Ꮑ")
zhrf1 = zhrf1:gsub("o","Ꭷ")
zhrf1 = zhrf1:gsub("O","Ꭷ")
zhrf1 = zhrf1:gsub("p","Ꭾ")
zhrf1 = zhrf1:gsub("P","Ꭾ")
zhrf1 = zhrf1:gsub("q","Ꮕ")
zhrf1 = zhrf1:gsub("Q","Ꮕ")
zhrf1 = zhrf1:gsub("r","ᖇ")
zhrf1 = zhrf1:gsub("R","ᖇ")
zhrf1 = zhrf1:gsub("s","Ꮥ")
zhrf1 = zhrf1:gsub("S","Ꮥ")
zhrf1 = zhrf1:gsub("t","Ꮱ")
zhrf1 = zhrf1:gsub("T","Ꮱ")
zhrf1 = zhrf1:gsub("u","Ꮼ")
zhrf1 = zhrf1:gsub("U","Ꮼ")
zhrf1 = zhrf1:gsub("v","Ꮙ")
zhrf1 = zhrf1:gsub("V","Ꮙ")
zhrf1 = zhrf1:gsub("w","Ꮗ")
zhrf1 = zhrf1:gsub("W","Ꮗ")
zhrf1 = zhrf1:gsub("x","Ꮂ")
zhrf1 = zhrf1:gsub("X","Ꮂ")
zhrf1 = zhrf1:gsub("y","Ꮍ")
zhrf1 = zhrf1:gsub("Y","Ꮍ")
zhrf1 = zhrf1:gsub("z","ᔓ")
zhrf1 = zhrf1:gsub("Z","ᔓ")

local zhrf2 = text:gsub('ض', 'ضَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('ص', 'صَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('ث', 'ثَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('ق', 'قَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('ف', 'فَٰ͒ـُـٰٓ')
zhrf2 = zhrf2:gsub('غ', 'غَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('ع', 'عَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('خ', 'خَٰ̐ـُـٰٓ')
zhrf2 = zhrf2:gsub('ح', 'حَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('ج', 'جَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('ش', 'شَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('س', 'سَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('ي', 'يَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('ب', 'بَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('ل', 'لَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('ا', 'آ')
zhrf2 = zhrf2:gsub('ت', 'تَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('ن', 'نَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('م', 'مَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('ك', 'ڪَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('ط', 'طَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('ظ', 'ظَٰـُـٰٓ')
zhrf2 = zhrf2:gsub('ء', 'ء')
zhrf2 = zhrf2:gsub('ؤ', 'ؤ')
zhrf2 = zhrf2:gsub('ر', 'ر')
zhrf2 = zhrf2:gsub('ى', 'ى')
zhrf2 = zhrf2:gsub('ز', 'ز')
zhrf2 = zhrf2:gsub('و', 'ﯛ̲୭')
zhrf2 = zhrf2:gsub("ه", "ۿۿہ")
zhrf2 = zhrf2:gsub('a', 'Á')
zhrf2 = zhrf2:gsub('b', 'ß')
zhrf2 = zhrf2:gsub('c', 'Č')
zhrf2 = zhrf2:gsub('d', 'Ď')
zhrf2 = zhrf2:gsub('e', 'Ĕ')
zhrf2 = zhrf2:gsub('f', 'Ŧ')
zhrf2 = zhrf2:gsub('g', 'Ğ')
zhrf2 = zhrf2:gsub('h', 'Ĥ')
zhrf2 = zhrf2:gsub('i', 'Ĩ')
zhrf2 = zhrf2:gsub('j', 'Ĵ')
zhrf2 = zhrf2:gsub('k', 'Ķ')
zhrf2 = zhrf2:gsub('l', 'Ĺ')
zhrf2 = zhrf2:gsub('m', 'M')
zhrf2 = zhrf2:gsub('n', 'Ń')
zhrf2 = zhrf2:gsub('o', 'Ő')
zhrf2 = zhrf2:gsub('p', 'P')
zhrf2 = zhrf2:gsub('q', 'Q')
zhrf2 = zhrf2:gsub('r', 'Ŕ')
zhrf2 = zhrf2:gsub('s', 'Ś')
zhrf2 = zhrf2:gsub('t', 'Ť')
zhrf2 = zhrf2:gsub('u', 'Ú')
zhrf2 = zhrf2:gsub('v', 'V')
zhrf2 = zhrf2:gsub('w', 'Ŵ')
zhrf2 = zhrf2:gsub('x', 'Ж')
zhrf2 = zhrf2:gsub('y', 'Ŷ')
zhrf2 = zhrf2:gsub('z', 'Ź') 


local zhrf3 = text:gsub('ض', 'ض')
zhrf3 = zhrf3:gsub('ص', 'ص')
zhrf3 = zhrf3:gsub('ث', 'ثہ')
zhrf3 = zhrf3:gsub('ق', 'ق')
zhrf3 = zhrf3:gsub('ف', 'فُہ')
zhrf3 = zhrf3:gsub('غ', 'غہ')
zhrf3 = zhrf3:gsub('ع', 'عہ')
zhrf3 = zhrf3:gsub('ه', 'هٰہٰٖ')
zhrf3 = zhrf3:gsub('خ', 'خہ')
zhrf3 = zhrf3:gsub('ح', 'حہ')
zhrf3 = zhrf3:gsub('ج', 'جہ')
zhrf3 = zhrf3:gsub('د', 'د')
zhrf3 = zhrf3:gsub('ذ', 'ذ')
zhrf3 = zhrf3:gsub('ش', 'شہ')
zhrf3 = zhrf3:gsub('س', 'سہ')
zhrf3 = zhrf3:gsub('ي', 'يہ')
zhrf3 = zhrf3:gsub('ب', 'بّ')
zhrf3 = zhrf3:gsub('ل', 'لہ')
zhrf3 = zhrf3:gsub('ا', 'ا')
zhrf3 = zhrf3:gsub('ت', 'تہ')
zhrf3 = zhrf3:gsub('ن', 'نٰہٰٖ')
zhrf3 = zhrf3:gsub('م', 'مٰہٰٖ')
zhrf3 = zhrf3:gsub('ك', 'كُہ')
zhrf3 = zhrf3:gsub('ط', 'طہ')
zhrf3 = zhrf3:gsub('ئ', 'ئ ْٰ')
zhrf3 = zhrf3:gsub('ء', 'ء')
zhrf3 = zhrf3:gsub('ؤ', 'ؤ')
zhrf3 = zhrf3:gsub('ر', 'رَ')
zhrf3 = zhrf3:gsub('لا', 'لہا')
zhrf3 = zhrf3:gsub('ى', 'ىْ')
zhrf3 = zhrf3:gsub('ة', 'ة')
zhrf3 = zhrf3:gsub('و', 'و')
zhrf3 = zhrf3:gsub('ز', 'ز')
zhrf3 = zhrf3:gsub('ظ', 'ظۗہٰٰ')
zhrf3 = zhrf3:gsub('q', 'Ꝙ')
zhrf3 = zhrf3:gsub('Q', 'Ꝙ')
zhrf3 = zhrf3:gsub('w', 'ᾧ')
zhrf3 = zhrf3:gsub('W', 'ᾧ')
zhrf3 = zhrf3:gsub('e', 'ἔ')
zhrf3 = zhrf3:gsub('E', 'ἔ')
zhrf3 = zhrf3:gsub('r', 'ʀ')
zhrf3 = zhrf3:gsub('R', 'ʀ')
zhrf3 = zhrf3:gsub('t', 'ҭ')
zhrf3 = zhrf3:gsub('T', 'ҭ')
zhrf3 = zhrf3:gsub('y', 'ẏ')
zhrf3 = zhrf3:gsub('Y', 'ẏ')
zhrf3 = zhrf3:gsub('u', 'ὗ')
zhrf3 = zhrf3:gsub('i', 'ἷ')
zhrf3 = zhrf3:gsub('o', 'ὄ')
zhrf3 = zhrf3:gsub('p', 'ῥ')
zhrf3 = zhrf3:gsub('a', 'ᾄ')
zhrf3 = zhrf3:gsub('s', 'ṩ')
zhrf3 = zhrf3:gsub('d', 'ḋ')
zhrf3 = zhrf3:gsub('f', 'ғ')
zhrf3 = zhrf3:gsub('g', 'ʛ')
zhrf3 = zhrf3:gsub('h', 'ђ')
zhrf3 = zhrf3:gsub('j', 'ʝ')
zhrf3 = zhrf3:gsub('k', 'ќ')
zhrf3 = zhrf3:gsub('U', 'ὗ')
zhrf3 = zhrf3:gsub('I', 'ἷ')
zhrf3 = zhrf3:gsub('O', 'ὄ')
zhrf3 = zhrf3:gsub('P', 'ῥ')
zhrf3 = zhrf3:gsub('A', 'ᾄ')
zhrf3 = zhrf3:gsub('S', 'ṩ')
zhrf3 = zhrf3:gsub('D', 'ḋ')
zhrf3 = zhrf3:gsub('F', 'ғ')
zhrf3 = zhrf3:gsub('G', 'ʛ')
zhrf3 = zhrf3:gsub('H', 'ђ')
zhrf3 = zhrf3:gsub('J', 'ʝ')
zhrf3 = zhrf3:gsub('K', 'ќ')
zhrf3 = zhrf3:gsub('L', 'ł')
zhrf3 = zhrf3:gsub('l', 'ł')
zhrf3 = zhrf3:gsub('z', 'ẓ')
zhrf3 = zhrf3:gsub('Z', 'ẓ')
zhrf3 = zhrf3:gsub('x', 'ẋ')
zhrf3 = zhrf3:gsub('X', 'ẋ')
zhrf3 = zhrf3:gsub('c', 'ƈ')
zhrf3 = zhrf3:gsub('C', 'ƈ')
zhrf3 = zhrf3:gsub('v', 'v')
zhrf3 = zhrf3:gsub('V', 'v')
zhrf3 = zhrf3:gsub('b', 'в')
zhrf3 = zhrf3:gsub('B', 'в')
zhrf3 = zhrf3:gsub('n', 'ᾗ')
zhrf3 = zhrf3:gsub('N', 'ᾗ')
zhrf3 = zhrf3:gsub('m', 'м')
zhrf3 = zhrf3:gsub('M', 'м')

local zhrf4 = text:gsub('ض', 'ضـٰ̲ـہۜہٰٰ')
zhrf4 = zhrf4:gsub('ص', 'صـٰ̲ـہۛہٰٰ')
zhrf4 = zhrf4:gsub('ث', 'ثـٰ̲ـہہٰٰ')
zhrf4 = zhrf4:gsub('ق', 'قـٰ̲ـہྀ̲ہٰٰ')
zhrf4 = zhrf4:gsub('ف', 'فـٰ̲ـہ͒ہٰٰ')
zhrf4 = zhrf4:gsub('غ', 'غـٰ̲ـہہٰٰ')
zhrf4 = zhrf4:gsub('ع', 'غـٰ̲ـہہٰٰ')
zhrf4 = zhrf4:gsub('ه', 'هٰہٰٖ')
zhrf4 = zhrf4:gsub('خ', 'خـٰ̲ـہٰ̐ہ ')
zhrf4 = zhrf4:gsub('ح', 'حـٰ̲ـہہٰٰ')
zhrf4 = zhrf4:gsub('ج', 'جـٰ̲ـہْۧ')
zhrf4 = zhrf4:gsub('د', 'دٰ')
zhrf4 = zhrf4:gsub('ذ', 'ذِٰ')
zhrf4 = zhrf4:gsub('ش', 'شـٰ̲ـہِٰہٰٰ')
zhrf4 = zhrf4:gsub('س', 'شـٰ̲ـہِٰہٰٰ')
zhrf4 = zhrf4:gsub('ي', 'شـٰ̲ـہِٰہٰٰ')
zhrf4 = zhrf4:gsub('ب', 'بـٰ̲ـہّہ')
zhrf4 = zhrf4:gsub('ل', 'لـٰ̲ـہ')
zhrf4 = zhrf4:gsub('ا', 'آ')
zhrf4 = zhrf4:gsub('ت', 'تـٰ̲ـہَہَٰ')
zhrf4 = zhrf4:gsub('ن', 'نـٰ̲ـہَِہ')
zhrf4 = zhrf4:gsub('م', 'مـٰ̲ـہٰ̲ہ')
zhrf4 = zhrf4:gsub('ك', 'ڪٰྀہٰٰ')
zhrf4 = zhrf4:gsub('ط', 'طـٰ̲ـہۨہٰٰ')
zhrf4 = zhrf4:gsub('ئ', 'ئ ْٰ')
zhrf4 = zhrf4:gsub('ء', 'ء')
zhrf4 = zhrf4:gsub('ؤ', 'ؤ')
zhrf4 = zhrf4:gsub('ر', 'رَ')
zhrf4 = zhrf4:gsub('لا', 'لہا')
zhrf4 = zhrf4:gsub('ى', 'ىْ')
zhrf4 = zhrf4:gsub('ة', 'ة')
zhrf4 = zhrf4:gsub('و', 'وِٰ')
zhrf4 = zhrf4:gsub('ز', 'زَٰ')
zhrf4 = zhrf4:gsub('ظ', 'ظۗہٰٰ')
zhrf4 = zhrf4:gsub('q', 'Ꝙ')
zhrf4 = zhrf4:gsub('Q', 'Ꝙ')
zhrf4 = zhrf4:gsub('w', 'Ɯ')
zhrf4 = zhrf4:gsub('W', 'Ɯ')
zhrf4 = zhrf4:gsub('e', 'Є')
zhrf4 = zhrf4:gsub('E', 'Є')
zhrf4 = zhrf4:gsub('r', 'Ʀ')
zhrf4 = zhrf4:gsub('R', 'Ʀ')
zhrf4 = zhrf4:gsub('t', 'Ƭ')
zhrf4 = zhrf4:gsub('T', 'Ƭ')
zhrf4 = zhrf4:gsub('y', 'Ƴ')
zhrf4 = zhrf4:gsub('Y', 'Ƴ')
zhrf4 = zhrf4:gsub('u', 'Ʋ')
zhrf4 = zhrf4:gsub('i', 'Ɩ')
zhrf4 = zhrf4:gsub('o', 'Ơ')
zhrf4 = zhrf4:gsub('p', 'Ƥ')
zhrf4 = zhrf4:gsub('a', 'ƛ')
zhrf4 = zhrf4:gsub('s', 'Ƨ')
zhrf4 = zhrf4:gsub('d', 'Ɗ')
zhrf4 = zhrf4:gsub('f', 'Ƒ')
zhrf4 = zhrf4:gsub('g', 'Ɠ')
zhrf4 = zhrf4:gsub('h', 'Ӈ')
zhrf4 = zhrf4:gsub('j', 'ʆ')
zhrf4 = zhrf4:gsub('k', 'Ƙ')
zhrf4 = zhrf4:gsub('U', 'Ʋ')
zhrf4 = zhrf4:gsub('I', 'Ɩ')
zhrf4 = zhrf4:gsub('O', 'Ơ')
zhrf4 = zhrf4:gsub('P', 'Ƥ')
zhrf4 = zhrf4:gsub('A', 'ƛ')
zhrf4 = zhrf4:gsub('S', 'Ƨ')
zhrf4 = zhrf4:gsub('D', 'ḋ')
zhrf4 = zhrf4:gsub('F', 'ғ')
zhrf4 = zhrf4:gsub('G', 'ʛ')
zhrf4 = zhrf4:gsub('H', 'ђ')
zhrf4 = zhrf4:gsub('J', 'ʝ')
zhrf4 = zhrf4:gsub('K', 'ќ')
zhrf4 = zhrf4:gsub('L', 'Լ')
zhrf4 = zhrf4:gsub('l', 'Լ')
zhrf4 = zhrf4:gsub('z', 'Ȥ')
zhrf4 = zhrf4:gsub('Z', 'Ȥ')
zhrf4 = zhrf4:gsub('x', 'Ҳ')
zhrf4 = zhrf4:gsub('X', 'Ҳ')
zhrf4 = zhrf4:gsub('c', 'Ƈ')
zhrf4 = zhrf4:gsub('C', 'Ƈ')
zhrf4 = zhrf4:gsub('v', 'Ɣ')
zhrf4 = zhrf4:gsub('V', 'Ɣ')
zhrf4 = zhrf4:gsub('b', 'Ɓ')
zhrf4 = zhrf4:gsub('B', 'Ɓ')
zhrf4 = zhrf4:gsub('n', 'Ɲ')
zhrf4 = zhrf4:gsub('N', 'Ɲ')
zhrf4 = zhrf4:gsub('m', 'M')
zhrf4 = zhrf4:gsub('M', 'M')

local zhrf5 = text:gsub('ض', 'ضۜہٰٰ')
zhrf5 = zhrf5:gsub('ص', 'ضۜہٰٰ')
zhrf5 = zhrf5:gsub('ث', 'ثہٰٰ')
zhrf5 = zhrf5:gsub('ق', 'قྀ̲ہٰٰ')
zhrf5 = zhrf5:gsub('ف', 'ف͒ہٰٰ')
zhrf5 = zhrf5:gsub('غ', 'غہٰٰ')
zhrf5 = zhrf5:gsub('ع', 'عہٰٰ')
zhrf5 = zhrf5:gsub('ه', 'هٰہٰٖ')
zhrf5 = zhrf5:gsub('خ', 'خٰ̐ہ ')
zhrf5 = zhrf5:gsub('ح', 'حہٰٰ')
zhrf5 = zhrf5:gsub('ج', 'جـٰ̲ـہْۧ')
zhrf5 = zhrf5:gsub('د', 'دٰ')
zhrf5 = zhrf5:gsub('ذ', 'ذِٰ')
zhrf5 = zhrf5:gsub('ش', 'شِٰہٰٰ')
zhrf5 = zhrf5:gsub('س', 'سٰٓ')
zhrf5 = zhrf5:gsub('ي', 'يِٰہ')
zhrf5 = zhrf5:gsub('ب', 'بّہ')
zhrf5 = zhrf5:gsub('ل', 'لـٰ̲ـہ')
zhrf5 = zhrf5:gsub('ا', 'آ')
zhrf5 = zhrf5:gsub('ت', 'تَہَٰ')
zhrf5 = zhrf5:gsub('ن', 'نَِہ')
zhrf5 = zhrf5:gsub('م', 'مٰ̲ہ')
zhrf5 = zhrf5:gsub('ك', 'ڪٰྀہٰٰ')
zhrf5 = zhrf5:gsub('ط', 'طۨہٰٰ')
zhrf5 = zhrf5:gsub('ئ', 'ئ ْٰ')
zhrf5 = zhrf5:gsub('ء', 'ء')
zhrf5 = zhrf5:gsub('ؤ', 'ؤ')
zhrf5 = zhrf5:gsub('ر', 'رَ')
zhrf5 = zhrf5:gsub('لا', 'لہا')
zhrf5 = zhrf5:gsub('ى', 'ىْ')
zhrf5 = zhrf5:gsub('ة', 'ة')
zhrf5 = zhrf5:gsub('و', 'وِٰ')
zhrf5 = zhrf5:gsub('ز', 'زَٰ')
zhrf5 = zhrf5:gsub('ظ', 'ظۗہٰٰ')
zhrf5 = zhrf5:gsub('a', 'ᴀ')
zhrf5 = zhrf5:gsub('b', 'ʙ')
zhrf5 = zhrf5:gsub('c', 'ᴄ')
zhrf5 = zhrf5:gsub('d', 'ᴅ')
zhrf5 = zhrf5:gsub('e', 'ᴇ')
zhrf5 = zhrf5:gsub('f', 'ᴈ')
zhrf5 = zhrf5:gsub('g', 'ɢ')
zhrf5 = zhrf5:gsub('h', 'ʜ')
zhrf5 = zhrf5:gsub('i', 'ɪ')
zhrf5 = zhrf5:gsub('j', 'ᴊ')
zhrf5 = zhrf5:gsub('k', 'ᴋ')
zhrf5 = zhrf5:gsub('l', 'ʟ')
zhrf5 = zhrf5:gsub('m', 'ᴍ')
zhrf5 = zhrf5:gsub('n', 'ɴ')
zhrf5 = zhrf5:gsub('o', 'ᴏ')
zhrf5 = zhrf5:gsub('p', 'ᴘ')
zhrf5 = zhrf5:gsub('q', 'ᴓ')
zhrf5 = zhrf5:gsub('r', 'ʀ')
zhrf5 = zhrf5:gsub('s', 'ᴤ')
zhrf5 = zhrf5:gsub('t', 'ᴛ')
zhrf5 = zhrf5:gsub('u', 'ᴜ')
zhrf5 = zhrf5:gsub('v', 'ᴠ')
zhrf5 = zhrf5:gsub('w', 'ᴡ')
zhrf5 = zhrf5:gsub('x', 'ᴥ')
zhrf5 = zhrf5:gsub('y', 'ʏ')
zhrf5 = zhrf5:gsub('z', 'ᴢ')


local zhrf6 = text:gsub('ض', 'ض͜ـ')
zhrf6 = zhrf6:gsub('ص', 'ص͜ـ')
zhrf6 = zhrf6:gsub('ث', 'ث͜ـ͜ـ')
zhrf6 = zhrf6:gsub('ق', 'ق͜ـ')
zhrf6 = zhrf6:gsub('ف', 'ف͒͜ـ')
zhrf6 = zhrf6:gsub('غ', 'غ͜ـ')
zhrf6 = zhrf6:gsub('ع', 'ع͜ـ')
zhrf6 = zhrf6:gsub('خ', 'خ̐͜ـ')
zhrf6 = zhrf6:gsub('ح', 'ح͜ـ')
zhrf6 = zhrf6:gsub('ج', 'ج͜ـ')
zhrf6 = zhrf6:gsub('ش', 'ش͜ـ')
zhrf6 = zhrf6:gsub('س', 'س͜ـ')
zhrf6 = zhrf6:gsub('ي', 'ي͜ـ')
zhrf6 = zhrf6:gsub('ب', 'ب͜ـ')
zhrf6 = zhrf6:gsub('ل', 'ل͜ـ')
zhrf6 = zhrf6:gsub('ا', 'آ')
zhrf6 = zhrf6:gsub('ت', 'ت͜ـ')
zhrf6 = zhrf6:gsub('ن', 'ن͜ـ')
zhrf6 = zhrf6:gsub('م', 'م͜ـ')
zhrf6 = zhrf6:gsub('ك', 'ڪ͜ـ')
zhrf6 = zhrf6:gsub('ط', 'ط͜ـ')
zhrf6 = zhrf6:gsub('ظ', 'ظ͜ـ')
zhrf6 = zhrf6:gsub('ء', 'ء')
zhrf6 = zhrf6:gsub('ؤ', 'ؤ')
zhrf6 = zhrf6:gsub('ر', 'ر')
zhrf6 = zhrf6:gsub('ى', 'ى')
zhrf6 = zhrf6:gsub('ز', 'ز')
zhrf6 = zhrf6:gsub('ظ', 'ظـ')
zhrf6 = zhrf6:gsub('و', 'ﯛ̲୭')
zhrf6 = zhrf6:gsub("ه", "ۿۿہ")

zhrf6 = zhrf6:gsub('q', 'ƍ')
zhrf6 = zhrf6:gsub('Q', 'ƍ')
zhrf6 = zhrf6:gsub('w', 'w')
zhrf6 = zhrf6:gsub('W', 'w')
zhrf6 = zhrf6:gsub('e', 'È')
zhrf6 = zhrf6:gsub('E', 'È')
zhrf6 = zhrf6:gsub('r', 'r')
zhrf6 = zhrf6:gsub('R', 'r')
zhrf6 = zhrf6:gsub('t', '⊥')
zhrf6 = zhrf6:gsub('T', '⊥')
zhrf6 = zhrf6:gsub('y', 'ý')
zhrf6 = zhrf6:gsub('Y', 'ý')
zhrf6 = zhrf6:gsub('u', 'µ')
zhrf6 = zhrf6:gsub('U', 'µ')
zhrf6 = zhrf6:gsub('i', 'Î')
zhrf6 = zhrf6:gsub('I', 'Î')
zhrf6 = zhrf6:gsub('o', '◊')
zhrf6 = zhrf6:gsub('O', '◊')
zhrf6 = zhrf6:gsub('p', 'Ƿ')
zhrf6 = zhrf6:gsub('P', 'Ƿ')
zhrf6 = zhrf6:gsub('a', 'ª')
zhrf6 = zhrf6:gsub('A', 'ª')
zhrf6 = zhrf6:gsub('s', 'S')
zhrf6 = zhrf6:gsub('S', 'S')
zhrf6 = zhrf6:gsub('d', 'Þ')
zhrf6 = zhrf6:gsub('D', 'Þ')
zhrf6 = zhrf6:gsub('f', 'F')
zhrf6 = zhrf6:gsub('F', 'F')
zhrf6 = zhrf6:gsub('g', '૬')
zhrf6 = zhrf6:gsub('G', '૬')
zhrf6 = zhrf6:gsub('h', 'ɧ')
zhrf6 = zhrf6:gsub('H', 'ɧ')
zhrf6 = zhrf6:gsub('j', 'j')
zhrf6 = zhrf6:gsub('J', 'j')
zhrf6 = zhrf6:gsub('L', 'Ļ')
zhrf6 = zhrf6:gsub('l', 'Ļ')
zhrf6 = zhrf6:gsub('z', 'z')
zhrf6 = zhrf6:gsub('Z', 'z')
zhrf6 = zhrf6:gsub('x', '×')
zhrf6 = zhrf6:gsub('X', '×')
zhrf6 = zhrf6:gsub('c', '¢')
zhrf6 = zhrf6:gsub('C', '¢')
zhrf6 = zhrf6:gsub('v', '√')
zhrf6 = zhrf6:gsub('V', '√')
zhrf6 = zhrf6:gsub('b', 'b')
zhrf6 = zhrf6:gsub('B', 'b')
zhrf6 = zhrf6:gsub('n', 'η')
zhrf6 = zhrf6:gsub('N', 'η')
zhrf6 = zhrf6:gsub('m', 'м')
zhrf6 = zhrf6:gsub('M', 'м')

local zhrf7 = text:gsub('ض', 'ﺿ̭͠')
zhrf7 = zhrf7:gsub('ص', 'ﺻ͡')
zhrf7 = zhrf7:gsub('ث', 'ﺜ̲')
zhrf7 = zhrf7:gsub('ق', 'ﭰ')
zhrf7 = zhrf7:gsub('ف', 'ﻓ̲')
zhrf7 = zhrf7:gsub('غ', 'ﻏ̲')
zhrf7 = zhrf7:gsub('ع', 'ﻌ̲')
zhrf7 = zhrf7:gsub('ه', 'ﮬ̲̌')
zhrf7 = zhrf7:gsub('خ', 'خٌ')
zhrf7 = zhrf7:gsub('ح', 'ﺣ̅')
zhrf7 = zhrf7:gsub('ج', 'جُ')
zhrf7 = zhrf7:gsub('د', 'ډ̝')
zhrf7 = zhrf7:gsub('ذ', 'ذً')
zhrf7 = zhrf7:gsub('ش', 'ﺷ̲')
zhrf7 = zhrf7:gsub('س', 'ﺳ̉')
zhrf7 = zhrf7:gsub('ي', 'ﯾ̃̐')
zhrf7 = zhrf7:gsub('ب', 'ﺑ̲')
zhrf7 = zhrf7:gsub('ل', 'ا̄ﻟ')
zhrf7 = zhrf7:gsub('ا', 'ﺈ̃')
zhrf7 = zhrf7:gsub('ت', 'ټُ')
zhrf7 = zhrf7:gsub('ن', 'ﻧ̲')
zhrf7 = zhrf7:gsub('م', 'ﻣ̲̉')
zhrf7 = zhrf7:gsub('ك', 'گ')
zhrf7 = zhrf7:gsub('ط', 'ﻁ̲')
zhrf7 = zhrf7:gsub('ئ', ' ْٰئ')
zhrf7 = zhrf7:gsub('ء', 'ء')
zhrf7 = zhrf7:gsub('ؤ', 'ؤ')
zhrf7 = zhrf7:gsub('ر', 'ہڕ')
zhrf7 = zhrf7:gsub('لا', 'ﻟ̲ﺂ̲')
zhrf7 = zhrf7:gsub('ى', 'ى')
zhrf7 = zhrf7:gsub('ة', 'ة')
zhrf7 = zhrf7:gsub('و', 'ۇۈۉ')
zhrf7 = zhrf7:gsub('ز', 'زُ')
zhrf7 = zhrf7:gsub('ظ', 'ﻇ̲')
zhrf7 = zhrf7:gsub('q', 'Ⴓ')
zhrf7 = zhrf7:gsub('Q', 'Ⴓ')
zhrf7 = zhrf7:gsub('w', 'Ш')
zhrf7 = zhrf7:gsub('W', 'Ш')
zhrf7 = zhrf7:gsub('e', 'Σ')
zhrf7 = zhrf7:gsub('E', 'Σ')
zhrf7 = zhrf7:gsub('r', 'Γ')
zhrf7 = zhrf7:gsub('R', 'Γ')
zhrf7 = zhrf7:gsub('t', 'Ƭ')
zhrf7 = zhrf7:gsub('T', 'Ƭ')
zhrf7 = zhrf7:gsub('y', 'Ψ')
zhrf7 = zhrf7:gsub('Y', 'Ψ')
zhrf7 = zhrf7:gsub('u', 'Ʊ')
zhrf7 = zhrf7:gsub('U', 'Ʊ')
zhrf7 = zhrf7:gsub('i', 'I')
zhrf7 = zhrf7:gsub('I', 'I')
zhrf7 = zhrf7:gsub('o', 'Θ')
zhrf7 = zhrf7:gsub('O', 'Θ')
zhrf7 = zhrf7:gsub('p', 'Ƥ')
zhrf7 = zhrf7:gsub('P', 'Ƥ')
zhrf7 = zhrf7:gsub('a', 'Δ')
zhrf7 = zhrf7:gsub('A', 'Δ')
zhrf7 = zhrf7:gsub('s', 'Ѕ')
zhrf7 = zhrf7:gsub('S', 'Ѕ')
zhrf7 = zhrf7:gsub('d', 'D')
zhrf7 = zhrf7:gsub('D', 'D')
zhrf7 = zhrf7:gsub('f', 'F')
zhrf7 = zhrf7:gsub('F', 'F')
zhrf7 = zhrf7:gsub('g', 'G')
zhrf7 = zhrf7:gsub('G', 'G')
zhrf7 = zhrf7:gsub('h', 'H')
zhrf7 = zhrf7:gsub('H', 'H')
zhrf7 = zhrf7:gsub('j', 'J')
zhrf7 = zhrf7:gsub('J', 'J')
zhrf7 = zhrf7:gsub('L', 'L')
zhrf7 = zhrf7:gsub('l', 'L')
zhrf7 = zhrf7:gsub('z', 'Z')
zhrf7 = zhrf7:gsub('Z', 'Z')
zhrf7 = zhrf7:gsub('x', 'Ж')
zhrf7 = zhrf7:gsub('X', 'Ж')
zhrf7 = zhrf7:gsub('c', 'C')
zhrf7 = zhrf7:gsub('C', 'C')
zhrf7 = zhrf7:gsub('v', 'Ʋ')
zhrf7 = zhrf7:gsub('V', 'Ʋ')
zhrf7 = zhrf7:gsub('b', 'Ɓ')
zhrf7 = zhrf7:gsub('B', 'Ɓ')
zhrf7 = zhrf7:gsub('n', '∏')
zhrf7 = zhrf7:gsub('N', '∏')
zhrf7 = zhrf7:gsub('m', 'Μ')
zhrf7 = zhrf7:gsub('M', 'Μ')

local zhrf8 = text:gsub('ض', 'ضہ')
zhrf8 = zhrf8:gsub('ص', 'صہ')
zhrf8 = zhrf8:gsub('ث', 'ثہ')
zhrf8 = zhrf8:gsub('ق', 'قہ')
zhrf8 = zhrf8:gsub('ف', 'فہ')
zhrf8 = zhrf8:gsub('غ', 'غہ')
zhrf8 = zhrf8:gsub('ع', 'عہ')
zhrf8 = zhrf8:gsub('خ', 'خہ')
zhrf8 = zhrf8:gsub('ح', 'حہ')
zhrf8 = zhrf8:gsub('ج', 'جہ')
zhrf8 = zhrf8:gsub('ش', 'شہ')
zhrf8 = zhrf8:gsub('س', 'سہ')
zhrf8 = zhrf8:gsub('ي', 'يہ')
zhrf8 = zhrf8:gsub('ب', 'بہ')
zhrf8 = zhrf8:gsub('ل', 'ل')
zhrf8 = zhrf8:gsub('ا', 'آ')
zhrf8 = zhrf8:gsub('ت', 'تہ')
zhrf8 = zhrf8:gsub('ن', 'نہ')
zhrf8 = zhrf8:gsub('م', 'مہ')
zhrf8 = zhrf8:gsub('ك', 'كہ')
zhrf8 = zhrf8:gsub('ط', 'طہ')
zhrf8 = zhrf8:gsub('ظ', 'ظہ')
zhrf8 = zhrf8:gsub('ء', 'ء')
zhrf8 = zhrf8:gsub('ؤ', 'ؤ')
zhrf8 = zhrf8:gsub('ر', 'ر')
zhrf8 = zhrf8:gsub('ى', 'ى')
zhrf8 = zhrf8:gsub('ز', 'ز')
zhrf8 = zhrf8:gsub('و', 'ﯛ̲୭')
zhrf8 = zhrf8:gsub("ه", "ۿۿہ")

zhrf8 = zhrf8:gsub('q', '๑')
zhrf8 = zhrf8:gsub('Q', '๑')
zhrf8 = zhrf8:gsub('w', 'ຟ')
zhrf8 = zhrf8:gsub('W', 'ຟ')
zhrf8 = zhrf8:gsub('e', 'ē')
zhrf8 = zhrf8:gsub('E', 'ē')
zhrf8 = zhrf8:gsub('r', 'r')
zhrf8 = zhrf8:gsub('R', 'r')
zhrf8 = zhrf8:gsub('t', 't')
zhrf8 = zhrf8:gsub('T', 't')
zhrf8 = zhrf8:gsub('y', 'ฯ')
zhrf8 = zhrf8:gsub('Y', 'ฯ')
zhrf8 = zhrf8:gsub('u', 'น')
zhrf8 = zhrf8:gsub('U', 'น')
zhrf8 = zhrf8:gsub('i', 'i')
zhrf8 = zhrf8:gsub('I', 'i')
zhrf8 = zhrf8:gsub('o', '໐')
zhrf8 = zhrf8:gsub('O', '໐')
zhrf8 = zhrf8:gsub('p', 'p')
zhrf8 = zhrf8:gsub('P', 'p')
zhrf8 = zhrf8:gsub('a', 'ค')
zhrf8 = zhrf8:gsub('A', 'ค')
zhrf8 = zhrf8:gsub('s', 'Ş')
zhrf8 = zhrf8:gsub('S', 'Ş')
zhrf8 = zhrf8:gsub('d', '໓')
zhrf8 = zhrf8:gsub('D', '໓')
zhrf8 = zhrf8:gsub('f', 'f')
zhrf8 = zhrf8:gsub('F', 'f')
zhrf8 = zhrf8:gsub('g', 'ງ')
zhrf8 = zhrf8:gsub('G', 'ງ')
zhrf8 = zhrf8:gsub('h', 'h')
zhrf8 = zhrf8:gsub('H', 'h')
zhrf8 = zhrf8:gsub('j', 'ว')
zhrf8 = zhrf8:gsub('J', 'ว')
zhrf8 = zhrf8:gsub('k', 'k')
zhrf8 = zhrf8:gsub('K', 'k')
zhrf8 = zhrf8:gsub('L', 'l')
zhrf8 = zhrf8:gsub('l', 'l')
zhrf8 = zhrf8:gsub('z', 'ຊ')
zhrf8 = zhrf8:gsub('Z', 'ຊ')
zhrf8 = zhrf8:gsub('x', 'x')
zhrf8 = zhrf8:gsub('X', 'x')
zhrf8 = zhrf8:gsub('c', '¢')
zhrf8 = zhrf8:gsub('C', '¢')
zhrf8 = zhrf8:gsub('v', 'ง')
zhrf8 = zhrf8:gsub('V', 'ง')
zhrf8 = zhrf8:gsub('b', '๖')
zhrf8 = zhrf8:gsub('B', '๖')
zhrf8 = zhrf8:gsub('n', 'ຖ')
zhrf8 = zhrf8:gsub('N', 'ຖ')
zhrf8 = zhrf8:gsub('m', '๓')
zhrf8 = zhrf8:gsub('M', '๓')

local zhrf9 = text:gsub('ض', 'ض')
zhrf9 = zhrf9:gsub('ص', 'صہٰ')
zhrf9 = zhrf9:gsub('ث', 'ثہٰـ')
zhrf9 = zhrf9:gsub('ق', 'قہٰ')
zhrf9 = zhrf9:gsub('ف', 'فہٰ')
zhrf9 = zhrf9:gsub('غ', 'غـْ')
zhrf9 = zhrf9:gsub('ع', 'ع')
zhrf9 = zhrf9:gsub('ه', 'هٰہٰٖ')
zhrf9 = zhrf9:gsub('خ', 'خخَـ')
zhrf9 = zhrf9:gsub('ح', 'حہٰ')
zhrf9 = zhrf9:gsub('ج', 'ججہٰ')
zhrf9 = zhrf9:gsub('د', 'دَ')
zhrf9 = zhrf9:gsub('ذ', 'ذّ')
zhrf9 = zhrf9:gsub('ش', 'ششہٰ')
zhrf9 = zhrf9:gsub('س', 'سہٰ')
zhrf9 = zhrf9:gsub('ي', 'يٰ')
zhrf9 = zhrf9:gsub('ب', 'بٰٰ')
zhrf9 = zhrf9:gsub('ل', 'لہٰ')
zhrf9 = zhrf9:gsub('ا', 'آ')
zhrf9 = zhrf9:gsub('ت', 'تہٰ')
zhrf9 = zhrf9:gsub('ن', 'نہٰ')
zhrf9 = zhrf9:gsub('م', 'مہٰ')
zhrf9 = zhrf9:gsub('ك', 'ككہٰ')
zhrf9 = zhrf9:gsub('ط', 'طہٰ')
zhrf9 = zhrf9:gsub('ئ', ' ْئٰ')
zhrf9 = zhrf9:gsub('ء', 'ء')
zhrf9 = zhrf9:gsub('ؤ', 'ؤؤَ')
zhrf9 = zhrf9:gsub('ر', 'رَ')
zhrf9 = zhrf9:gsub('لا', 'لہٰا')
zhrf9 = zhrf9:gsub('ى', 'ىہٰ')
zhrf9 = zhrf9:gsub('ة', 'ة')
zhrf9 = zhrf9:gsub('و', 'ہٰو')
zhrf9 = zhrf9:gsub('ز', 'ز')
zhrf9 = zhrf9:gsub('ظ', 'ظہٰ')
zhrf9 = zhrf9:gsub('q', 'զ')
zhrf9 = zhrf9:gsub('Q', 'զ')
zhrf9 = zhrf9:gsub('w', 'ա')
zhrf9 = zhrf9:gsub('W', 'ա')
zhrf9 = zhrf9:gsub('e', 'ɛ')
zhrf9 = zhrf9:gsub('E', 'ɛ')
zhrf9 = zhrf9:gsub('r', 'ʀ')
zhrf9 = zhrf9:gsub('R', 'ʀ')
zhrf9 = zhrf9:gsub('t', 'ȶ')
zhrf9 = zhrf9:gsub('T', 'ȶ')
zhrf9 = zhrf9:gsub('y', 'ʏ')
zhrf9 = zhrf9:gsub('Y', 'ʏ')
zhrf9 = zhrf9:gsub('u', 'ʊ')
zhrf9 = zhrf9:gsub('U', 'ʊ')
zhrf9 = zhrf9:gsub('i', 'ɨ')
zhrf9 = zhrf9:gsub('I', 'ɨ')
zhrf9 = zhrf9:gsub('o', 'օ')
zhrf9 = zhrf9:gsub('O', 'օ')
zhrf9 = zhrf9:gsub('p', 'ք')
zhrf9 = zhrf9:gsub('P', 'ք')
zhrf9 = zhrf9:gsub('a', 'ǟ')
zhrf9 = zhrf9:gsub('A', 'ǟ')
zhrf9 = zhrf9:gsub('s', 'ֆ')
zhrf9 = zhrf9:gsub('S', 'ֆ')
zhrf9 = zhrf9:gsub('d', 'ɖ')
zhrf9 = zhrf9:gsub('D', 'ɖ')
zhrf9 = zhrf9:gsub('f', 'ʄ')
zhrf9 = zhrf9:gsub('F', 'ʄ')
zhrf9 = zhrf9:gsub('g', 'ɢ')
zhrf9 = zhrf9:gsub('G', 'ɢ')
zhrf9 = zhrf9:gsub('h', 'ɦ')
zhrf9 = zhrf9:gsub('H', 'ɦ')
zhrf9 = zhrf9:gsub('j', 'ʝ')
zhrf9 = zhrf9:gsub('J', 'ʝ')
zhrf9 = zhrf9:gsub('k', 'ӄ')
zhrf9 = zhrf9:gsub('K', 'ӄ')
zhrf9 = zhrf9:gsub('L', 'ʟ')
zhrf9 = zhrf9:gsub('l', 'ʟ')
zhrf9 = zhrf9:gsub('z', 'ʐ')
zhrf9 = zhrf9:gsub('Z', 'ʐ')
zhrf9 = zhrf9:gsub('x', 'Ӽ')
zhrf9 = zhrf9:gsub('X', 'Ӽ')
zhrf9 = zhrf9:gsub('c', 'ƈ')
zhrf9 = zhrf9:gsub('C', 'ƈ')
zhrf9 = zhrf9:gsub('v', 'ʋ')
zhrf9 = zhrf9:gsub('V', 'ʋ')
zhrf9 = zhrf9:gsub('b', 'ɮ')
zhrf9 = zhrf9:gsub('B', 'ɮ')
zhrf9 = zhrf9:gsub('n', 'ռ')
zhrf9 = zhrf9:gsub('N', 'ռ')
zhrf9 = zhrf9:gsub('m', 'ʍ')
zhrf9 = zhrf9:gsub('M', 'ʍ')

local zhrf10 = text:gsub('ض', 'ضِـٰٚـ')
zhrf10 = zhrf10:gsub('ص', 'صِـٰٚـ')
zhrf10 = zhrf10:gsub('ث', 'ثِـٰٚـ')
zhrf10 = zhrf10:gsub('ق', 'قِـٰٚـ')
zhrf10 = zhrf10:gsub('ف', 'فِ͒ـٰٚـ')
zhrf10 = zhrf10:gsub('غ', 'غِـٰٚـ')
zhrf10 = zhrf10:gsub('ع', 'عِـٰٚـ')
zhrf10 = zhrf10:gsub('خ', 'خِ̐ـٰٚـ')
zhrf10 = zhrf10:gsub('ح', 'حِـٰٚـ')
zhrf10 = zhrf10:gsub('ج', 'جِـٰٚـِِـٰٚـِْ')
zhrf10 = zhrf10:gsub('ش', 'شِـٰٚـ')
zhrf10 = zhrf10:gsub('س', 'سِـٰٚـ')
zhrf10 = zhrf10:gsub('ي', 'يِـٰٚـ')
zhrf10 = zhrf10:gsub('ب', 'بِـٰٚـ')
zhrf10 = zhrf10:gsub('ل', 'لِـٰٚـ')
zhrf10 = zhrf10:gsub('ا', 'آ')
zhrf10 = zhrf10:gsub('ت', 'تِـٰٚـ')
zhrf10 = zhrf10:gsub('ن', 'نِـٰٚـ')
zhrf10 = zhrf10:gsub('م', 'مِـٰٚـ')
zhrf10 = zhrf10:gsub('ك', 'ڪِـٰٚـ')
zhrf10 = zhrf10:gsub('ط', 'طِـٰٚـ')
zhrf10 = zhrf10:gsub('ذ', 'ذِـٰٚـ')
zhrf10 = zhrf10:gsub('ظ', 'ظِـٰٚـ')
zhrf10 = zhrf10:gsub('ء', 'ء')
zhrf10 = zhrf10:gsub('ؤ', 'ؤ')
zhrf10 = zhrf10:gsub('ر', 'ر')
zhrf10 = zhrf10:gsub('ى', 'ى')
zhrf10 = zhrf10:gsub('ز', 'ز')
zhrf10 = zhrf10:gsub('ظ', 'ظِـٰٚـ')
zhrf10 = zhrf10:gsub('و', 'ﯛ̲୭')
zhrf10 = zhrf10:gsub("ه", "ۿۿہ")
zhrf10 = zhrf10:gsub('q', 'Q')
zhrf10 = zhrf10:gsub('Q', 'Q')
zhrf10 = zhrf10:gsub('w', 'Ẃ')
zhrf10 = zhrf10:gsub('W', 'Ẃ')
zhrf10 = zhrf10:gsub('e', 'Ἕ')
zhrf10 = zhrf10:gsub('E', 'Ἕ')
zhrf10 = zhrf10:gsub('r', 'Ȓ')
zhrf10 = zhrf10:gsub('R', 'Ȓ')
zhrf10 = zhrf10:gsub('t', 'Ҭ')
zhrf10 = zhrf10:gsub('T', 'Ҭ')
zhrf10 = zhrf10:gsub('y', 'Ὓ')
zhrf10 = zhrf10:gsub('Y', 'Ὓ')
zhrf10 = zhrf10:gsub('u', 'Ȗ')
zhrf10 = zhrf10:gsub('U', 'Ȗ')
zhrf10 = zhrf10:gsub('i', 'Ἷ')
zhrf10 = zhrf10:gsub('I', 'Ἷ')
zhrf10 = zhrf10:gsub('o', 'Ὃ')
zhrf10 = zhrf10:gsub('O', 'Ὃ')
zhrf10 = zhrf10:gsub('p', 'Ƥ')
zhrf10 = zhrf10:gsub('P', 'Ƥ')
zhrf10 = zhrf10:gsub('a', 'ᾋ')
zhrf10 = zhrf10:gsub('A', 'ᾋ')
zhrf10 = zhrf10:gsub('s', 'Ṩ')
zhrf10 = zhrf10:gsub('S', 'Ṩ')
zhrf10 = zhrf10:gsub('d', 'Ɖ')
zhrf10 = zhrf10:gsub('D', 'Ɖ')
zhrf10 = zhrf10:gsub('f', 'Ғ')
zhrf10 = zhrf10:gsub('F', 'Ғ')
zhrf10 = zhrf10:gsub('g', 'Ɠ')
zhrf10 = zhrf10:gsub('G', 'Ɠ')
zhrf10 = zhrf10:gsub('h', 'Ἤ')
zhrf10 = zhrf10:gsub('H', 'Ἤ')
zhrf10 = zhrf10:gsub('j', 'Ј')
zhrf10 = zhrf10:gsub('J', 'Ј')
zhrf10 = zhrf10:gsub('k', 'Ḱ')
zhrf10 = zhrf10:gsub('K', 'Ḱ')
zhrf10 = zhrf10:gsub('L', 'Ŀ')
zhrf10 = zhrf10:gsub('l', 'Ŀ')
zhrf10 = zhrf10:gsub('z', 'Ẕ')
zhrf10 = zhrf10:gsub('Z', 'Ẕ')
zhrf10 = zhrf10:gsub('x', 'Ẋ')
zhrf10 = zhrf10:gsub('X', 'Ẋ')
zhrf10 = zhrf10:gsub('c', 'Ƈ')
zhrf10 = zhrf10:gsub('C', 'Ƈ')
zhrf10 = zhrf10:gsub('v', 'V')
zhrf10 = zhrf10:gsub('V', 'V')
zhrf10 = zhrf10:gsub('b', 'ϐ')
zhrf10 = zhrf10:gsub('B', 'ϐ')
zhrf10 = zhrf10:gsub('n', 'Ɲ')
zhrf10 = zhrf10:gsub('N', 'Ɲ')
zhrf10 = zhrf10:gsub('m', 'Ṃ')
zhrf10 = zhrf10:gsub('M', 'Ṃ')

local zhrf11 = text:gsub("q", "q")
zhrf11 = zhrf11:gsub("Q", "q")
zhrf11 = zhrf11:gsub("w", "ω")
zhrf11 = zhrf11:gsub("W", "ω")
zhrf11 = zhrf11:gsub("e", "ε")
zhrf11 = zhrf11:gsub("E", "ε")
zhrf11 = zhrf11:gsub("r", "я")
zhrf11 = zhrf11:gsub("R", "я")
zhrf11 = zhrf11:gsub("T", "т")
zhrf11 = zhrf11:gsub("t", "т")
zhrf11 = zhrf11:gsub("y", "ү")
zhrf11 = zhrf11:gsub("Y", "ү")
zhrf11 = zhrf11:gsub("u", "υ")
zhrf11 = zhrf11:gsub("U", "υ")
zhrf11 = zhrf11:gsub("i", "ι")
zhrf11 = zhrf11:gsub("I", "ι")
zhrf11 = zhrf11:gsub("o", "σ")
zhrf11 = zhrf11:gsub("O", "σ")
zhrf11 = zhrf11:gsub("p", "ρ")
zhrf11 = zhrf11:gsub("P", "ρ")
zhrf11 = zhrf11:gsub("a", "α")
zhrf11 = zhrf11:gsub("A", "α")
zhrf11 = zhrf11:gsub("s", "s")
zhrf11 = zhrf11:gsub("S", "s")
zhrf11 = zhrf11:gsub("d", "∂")
zhrf11 = zhrf11:gsub("D", "∂")
zhrf11 = zhrf11:gsub("f", "ғ")
zhrf11 = zhrf11:gsub("F", "ғ")
zhrf11 = zhrf11:gsub("g", "g")
zhrf11 = zhrf11:gsub("G", "g")
zhrf11 = zhrf11:gsub("h", "н")
zhrf11 = zhrf11:gsub("H", "н")
zhrf11 = zhrf11:gsub("j", "נ")
zhrf11 = zhrf11:gsub("J", "נ")
zhrf11 = zhrf11:gsub("k", "к")
zhrf11 = zhrf11:gsub("K", "к")
zhrf11 = zhrf11:gsub("l", "ℓ")
zhrf11 = zhrf11:gsub("L", "ℓ")
zhrf11 = zhrf11:gsub("z", "z")
zhrf11 = zhrf11:gsub("Z", "z")
zhrf11 = zhrf11:gsub("d", "∂")
zhrf11 = zhrf11:gsub("D", "∂")
zhrf11 = zhrf11:gsub("x", "x")
zhrf11 = zhrf11:gsub("X", "x")
zhrf11 = zhrf11:gsub("c", "c")
zhrf11 = zhrf11:gsub("C", "c")
zhrf11 = zhrf11:gsub("v", "v")
zhrf11 = zhrf11:gsub("V", "v")
zhrf11 = zhrf11:gsub("b", "в")
zhrf11 = zhrf11:gsub("B", "в")
zhrf11 = zhrf11:gsub("n", "η")
zhrf11 = zhrf11:gsub("N", "η")
zhrf11 = zhrf11:gsub("M", "м")
zhrf11 = zhrf11:gsub("m", "м")
zhrf11 = zhrf11:gsub('ض', 'ضُ͠')
zhrf11 = zhrf11:gsub('ص', 'صّ͠')
zhrf11 = zhrf11:gsub('ث', 'ثُ͠')
zhrf11 = zhrf11:gsub('ق', 'ق͠')
zhrf11 = zhrf11:gsub('ف', 'ف͠')
zhrf11 = zhrf11:gsub('غ', 'غ͠')
zhrf11 = zhrf11:gsub('ع', 'ع͠')
zhrf11 = zhrf11:gsub('خ', 'ٌخ͠')
zhrf11 = zhrf11:gsub('ح', 'حُ͠')
zhrf11 = zhrf11:gsub('ج', 'جْ͠')
zhrf11 = zhrf11:gsub('ش', 'شِ͠')
zhrf11 = zhrf11:gsub('س', 'سِ͠')
zhrf11 = zhrf11:gsub('ي', 'ي͠')
zhrf11 = zhrf11:gsub('ب', 'بّ͠')
zhrf11 = zhrf11:gsub('ل', 'ل͠')
zhrf11 = zhrf11:gsub('ا', 'ا')
zhrf11 = zhrf11:gsub('ت', 'تْ͠')
zhrf11 = zhrf11:gsub('ن', 'ن͠')
zhrf11 = zhrf11:gsub('م', 'م͠')
zhrf11 = zhrf11:gsub('ك', 'گ͠')
zhrf11 = zhrf11:gsub('طِ', 'ط͠')
zhrf11 = zhrf11:gsub('ظ', 'ظٌ͠')
zhrf11 = zhrf11:gsub('ء', '͠ء')
zhrf11 = zhrf11:gsub('وَ', 'و͠')
zhrf11 = zhrf11:gsub('ر', 'ر͠')
zhrf11 = zhrf11:gsub('ى', '͠ى')
zhrf11 = zhrf11:gsub('ز', 'ز͠')
zhrf11 = zhrf11:gsub('ض','ض͠')
zhrf11 = zhrf11:gsub('و', 'وَ͠')
zhrf11 = zhrf11:gsub("ه", "ه͠")

local zhrf12 = text:gsub('ا','آ')
zhrf12 = zhrf12:gsub("ب","بّہ")
zhrf12 = zhrf12:gsub("ت","تَہَٰ")
zhrf12 = zhrf12:gsub("ح","حہٰٰ")
zhrf12 = zhrf12:gsub("ج","جْۧ")
zhrf12 = zhrf12:gsub("خ","خٰ̐ہ")
zhrf12 = zhrf12:gsub("د","د")
zhrf12 = zhrf12:gsub("ذ","ذِ")
zhrf12 = zhrf12:gsub("ر","ر")
zhrf12 = zhrf12:gsub("ز","زَ")
zhrf12 = zhrf12:gsub("س","سٰٰٓ")
zhrf12 = zhrf12:gsub("ش","شِٰہٰٰ")
zhrf12 = zhrf12:gsub("ص","صۛہٰٰ")
zhrf12 = zhrf12:gsub("ض","ضۜہٰٰ")
zhrf12 = zhrf12:gsub("ظ","ظۗہٰٰ")
zhrf12 = zhrf12:gsub("غ","غہٰٰ")
zhrf12 = zhrf12:gsub("ف","ف͒ہٰٰ")
zhrf12 = zhrf12:gsub("ق","قྀ̲ہٰٰٰ")
zhrf12 = zhrf12:gsub("ك","ڪٰྀہٰٰٖ")
zhrf12 = zhrf12:gsub("ل","ل")
zhrf12 = zhrf12:gsub("ن","نَِٰہٰ")
zhrf12 = zhrf12:gsub("ه","ھہ")
zhrf12 = zhrf12:gsub("و","وِ")
zhrf12 = zhrf12:gsub("طۨہٰٰ","ط")
zhrf12 = zhrf12:gsub("ث","ثہٰٰ")
zhrf12 = zhrf12:gsub("ي","يِٰہ")
zhrf12 = zhrf12:gsub("ع","؏ۤـہٰٰ")
zhrf12 = zhrf12:gsub('a', '۰۪۫A۪۫۰')
zhrf12 = zhrf12:gsub('b', '۰۪۫B۪۫۰')
zhrf12 = zhrf12:gsub('c', '۰۪۫C۪۫۰')
zhrf12 = zhrf12:gsub('d', '۰۪۫D۪۫۰')
zhrf12 = zhrf12:gsub('e', '۰۪۫E۪۫۰')
zhrf12 = zhrf12:gsub('f', '۰۪۫F۪۫۰')
zhrf12 = zhrf12:gsub('g', '۰۪۫G۪۫۰')
zhrf12 = zhrf12:gsub('h', '۰۪۫H۪۫۰')
zhrf12 = zhrf12:gsub('i', '۰۪۫I۪۫۰')
zhrf12 = zhrf12:gsub('j', '۰۪۫J۪۫۰')
zhrf12 = zhrf12:gsub('k', '۰۪۫K۪۫۰')
zhrf12 = zhrf12:gsub('l', '۰۪۫L۪۫۰')
zhrf12 = zhrf12:gsub('m', '۰۪۫M۪۫۰')
zhrf12 = zhrf12:gsub('n', '۰۪۫N۪۫۰')
zhrf12 = zhrf12:gsub('o', '۰۪۫O۪۫۰')
zhrf12 = zhrf12:gsub('p', '۰۪۫P۪۫۰')
zhrf12 = zhrf12:gsub('q', '۰۪۫Q۪۫۰')
zhrf12 = zhrf12:gsub('r', '۰۪۫R۪۫۰')
zhrf12 = zhrf12:gsub('s', '۰۪۫S۪۫۰')
zhrf12 = zhrf12:gsub('t', '۰۪۫T۪۫۰')
zhrf12 = zhrf12:gsub('u', '۰۪۫U۪۫۰')
zhrf12 = zhrf12:gsub('v', '۰۪۫V۪۫۰')
zhrf12 = zhrf12:gsub('w', '۰۪۫W۪۫۰')
zhrf12 = zhrf12:gsub('x', '۰۪۫X۪۫۰')
zhrf12 = zhrf12:gsub('y', '۰۪۫Y۪۫۰')
zhrf12 = zhrf12:gsub('z', '۰۪۫Z۪۫۰')

local zhrf13 = text:gsub('a', 'ᾋ')
zhrf13 = zhrf13:gsub('b', 'ϐ')
zhrf13 = zhrf13:gsub('c', 'Ƈ')
zhrf13 = zhrf13:gsub('d', 'Ɖ')
zhrf13 = zhrf13:gsub('e', 'Ἕ')
zhrf13 = zhrf13:gsub('f', 'Ғ')
zhrf13 = zhrf13:gsub('g', 'Ɠ')
zhrf13 = zhrf13:gsub('h', 'Ἤ')
zhrf13 = zhrf13:gsub('i', 'Ἷ')
zhrf13 = zhrf13:gsub('j', 'Ј')
zhrf13 = zhrf13:gsub('k', 'Ḱ')
zhrf13 = zhrf13:gsub('l', 'Ŀ')
zhrf13 = zhrf13:gsub('m', 'Ṃ')
zhrf13 = zhrf13:gsub('n', 'Ɲ')
zhrf13 = zhrf13:gsub('o', 'Ὃ')
zhrf13 = zhrf13:gsub('p', 'Ƥ')
zhrf13 = zhrf13:gsub('q', 'Q')
zhrf13 = zhrf13:gsub('r', 'Ȓ')
zhrf13 = zhrf13:gsub('s', 'Ṩ')
zhrf13 = zhrf13:gsub('t', 'Ҭ')
zhrf13 = zhrf13:gsub('u', 'Ȗ')
zhrf13 = zhrf13:gsub('v', 'V')
zhrf13 = zhrf13:gsub('w', 'Ẃ')
zhrf13 = zhrf13:gsub('x', 'Ẋ')
zhrf13 = zhrf13:gsub('y', 'Ὓ')
zhrf13 = zhrf13:gsub('z', 'Ẕ')
zhrf13 = zhrf13:gsub('ض', 'ضـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ص', 'ص͜ہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ث', 'ث͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ق', 'ق͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ف', 'ف͒͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('غ', 'غ͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ع', 'ع͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('خ', 'خ̐͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ح', 'ح͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ج', 'ج͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ش', 'ش͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('س', 'س͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ي', 'ي͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ب', 'ب͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ل', 'ل͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ا', 'ا')
zhrf13 = zhrf13:gsub('ت', 'ت͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ن', 'ن͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('م', 'م͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ك', 'ڪ͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ط', 'ط͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ظ', 'ظ͜ـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('ء', 'ء')
zhrf13 = zhrf13:gsub('ؤ', 'ؤ')
zhrf13 = zhrf13:gsub('ر', 'ر')
zhrf13 = zhrf13:gsub('ى', 'ى')
zhrf13 = zhrf13:gsub('ز', 'ز')
zhrf13 = zhrf13:gsub('ظ', 'ظـہۣۣۗۗ')
zhrf13 = zhrf13:gsub('و', 'ﯛ̲୭')
zhrf13 = zhrf13:gsub("ه", "ۿۿہ")

local zhrf14 = text:gsub('ض', 'ضٰـہٰٖ')
zhrf14 = zhrf14:gsub('ص', 'صٰـہٰٖ')
zhrf14 = zhrf14:gsub('ث', 'ثٰـہٰٖ')
zhrf14 = zhrf14:gsub('ق', 'قٰـہٰٖ')
zhrf14 = zhrf14:gsub('ف', 'فٰـہٰٖ')
zhrf14 = zhrf14:gsub('غ', 'غٰـہٰٖ')
zhrf14 = zhrf14:gsub('خ', 'خٰـہٰٖ')
zhrf14 = zhrf14:gsub('ح', 'حٰـہٰٖ')
zhrf14 = zhrf14:gsub('ج', 'جٰـہٰٖ')
zhrf14 = zhrf14:gsub('ش', 'شٰـہٰٖ')
zhrf14 = zhrf14:gsub('س', 'سٰـہٰٖ')
zhrf14 = zhrf14:gsub('ي', 'يٰـہٰٖ')
zhrf14 = zhrf14:gsub('ب', 'بٰـہٰٖ')
zhrf14 = zhrf14:gsub('ل', 'لـہٰٖ')
zhrf14 = zhrf14:gsub('ا', 'ا')
zhrf14 = zhrf14:gsub('ت', 'تٰـہٰٖ')
zhrf14 = zhrf14:gsub('ن', 'نٰـہٰٖ')
zhrf14 = zhrf14:gsub('م', 'مٰـہٰٖ')
zhrf14 = zhrf14:gsub('ك', 'كٰـہٰٖ')
zhrf14 = zhrf14:gsub('ط', 'طٰـہٰٖ')
zhrf14 = zhrf14:gsub('ظ', 'ظٰـہٰٖ')
zhrf14 = zhrf14:gsub('ء', 'ء')
zhrf14 = zhrf14:gsub('ؤ', 'ؤ')
zhrf14 = zhrf14:gsub('ر', 'ر')
zhrf14 = zhrf14:gsub('ى', 'ى')
zhrf14 = zhrf14:gsub('ز', 'ز')
zhrf14 = zhrf14:gsub('و', 'ﯛ̲୭')
zhrf14 = zhrf14:gsub("ه", "໋۠هہؚ")
zhrf14 = zhrf14:gsub('a', 'ᴀ')
zhrf14 = zhrf14:gsub('b', 'ʙ')
zhrf14 = zhrf14:gsub('c', 'ᴄ')
zhrf14 = zhrf14:gsub('d', 'ᴅ')
zhrf14 = zhrf14:gsub('e', 'ᴇ')
zhrf14 = zhrf14:gsub('f', 'ғ')
zhrf14 = zhrf14:gsub('g', 'ɢ')
zhrf14 = zhrf14:gsub('h', 'ʜ')
zhrf14 = zhrf14:gsub('i', 'ɪ')
zhrf14 = zhrf14:gsub('j', 'ᴊ')
zhrf14 = zhrf14:gsub('k', 'ᴋ')
zhrf14 = zhrf14:gsub('l', 'ʟ')
zhrf14 = zhrf14:gsub('m', 'ᴍ')
zhrf14 = zhrf14:gsub('n', 'ɴ')
zhrf14 = zhrf14:gsub('o', 'ᴏ')
zhrf14 = zhrf14:gsub('p', 'ᴘ')
zhrf14 = zhrf14:gsub('q', 'ǫ')
zhrf14 = zhrf14:gsub('r', 'ʀ')
zhrf14 = zhrf14:gsub('s', 's')
zhrf14 = zhrf14:gsub('t', 'ᴛ')
zhrf14 = zhrf14:gsub('u', 'ᴜ')
zhrf14 = zhrf14:gsub('v', 'ᴠ')
zhrf14 = zhrf14:gsub('w', 'ᴡ')
zhrf14 = zhrf14:gsub('x', 'x')
zhrf14 = zhrf14:gsub('y', 'ʏ')
zhrf14 = zhrf14:gsub('z', 'ᴢ')

local zhrf15 = text:gsub('ض', 'ض͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ص', 'ص͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ث', 'ث͜ــ๋͜ـ͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ق', 'ق͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ف', 'ف͒͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('غ', 'غ͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ع', 'ع͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('خ', 'خ̐͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ح', 'ح͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ج', 'ج͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ش', 'ش͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('س', 'س͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ي', 'ي͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ب', 'ب͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ل', 'ل͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ا', 'ا')
zhrf15 = zhrf15:gsub('ت', 'ت͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ن', 'ن͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('م', 'م͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ك', 'ڪ͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ط', 'ط͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ظ', 'ظ͜ــ๋͜ـ')
zhrf15 = zhrf15:gsub('ء', 'ء')
zhrf15 = zhrf15:gsub('ؤ', 'ؤ')
zhrf15 = zhrf15:gsub('ر', 'ر')
zhrf15 = zhrf15:gsub('ى', 'ى')
zhrf15 = zhrf15:gsub('ز', 'ز')
zhrf15 = zhrf15:gsub('ظ', 'ظــ๋͜ـ')
zhrf15 = zhrf15:gsub('و', 'ﯛ̲୭')
zhrf15 = zhrf15:gsub("ه", "ۿۿہ")
zhrf15 = zhrf15:gsub('a', 'A꯭')
zhrf15 = zhrf15:gsub('b', 'B꯭')
zhrf15 = zhrf15:gsub('c', 'C꯭')
zhrf15 = zhrf15:gsub('d', 'D꯭')
zhrf15 = zhrf15:gsub('e', 'E꯭')
zhrf15 = zhrf15:gsub('f', 'F꯭')
zhrf15 = zhrf15:gsub('g', 'G꯭')
zhrf15 = zhrf15:gsub('h', 'H꯭')
zhrf15 = zhrf15:gsub('i', 'I꯭')
zhrf15 = zhrf15:gsub('j', 'J꯭')
zhrf15 = zhrf15:gsub('k', 'K꯭')
zhrf15 = zhrf15:gsub('l', 'L꯭')
zhrf15 = zhrf15:gsub('m', 'M꯭')
zhrf15 = zhrf15:gsub('n', 'N꯭')
zhrf15 = zhrf15:gsub('o', 'O꯭')
zhrf15 = zhrf15:gsub('p', 'P꯭')
zhrf15 = zhrf15:gsub('q', 'Q꯭')
zhrf15 = zhrf15:gsub('r', 'R꯭')
zhrf15 = zhrf15:gsub('s', 'S꯭')
zhrf15 = zhrf15:gsub('t', 'T꯭')
zhrf15 = zhrf15:gsub('u', 'U꯭')
zhrf15 = zhrf15:gsub('v', 'V꯭')
zhrf15 = zhrf15:gsub('w', 'W꯭')
zhrf15 = zhrf15:gsub('x', 'X꯭')
zhrf15 = zhrf15:gsub('y', 'Y꯭')
zhrf15 = zhrf15:gsub('z', 'Z꯭')


local zhrf16 = text:gsub("q", "ǫ")
zhrf16 = zhrf16:gsub("w", "ω")
zhrf16 = zhrf16:gsub("e", "૯")
zhrf16 = zhrf16:gsub("r", "ʀ")
zhrf16 = zhrf16:gsub("t", "τ")
zhrf16 = zhrf16:gsub("y", "ყ")
zhrf16 = zhrf16:gsub("u", "υ")
zhrf16 = zhrf16:gsub("i", "เ")
zhrf16 = zhrf16:gsub("o", "๏")
zhrf16 = zhrf16:gsub("p", "ρ")
zhrf16 = zhrf16:gsub("a", "Δ")
zhrf16 = zhrf16:gsub("s", "ઽ")
zhrf16 = zhrf16:gsub("d", "ᴅ")
zhrf16 = zhrf16:gsub("f", "ƒ")
zhrf16 = zhrf16:gsub("g", "ɢ")
zhrf16 = zhrf16:gsub("h", "み")
zhrf16 = zhrf16:gsub("j", "ʝ")
zhrf16 = zhrf16:gsub("k", "ҡ")
zhrf16 = zhrf16:gsub("l", "ɭ")
zhrf16 = zhrf16:gsub("z", "ʑ")
zhrf16 = zhrf16:gsub("x", "ﾒ")
zhrf16 = zhrf16:gsub("c", "૮")
zhrf16 = zhrf16:gsub("v", "ѵ")
zhrf16 = zhrf16:gsub("b", "β")
zhrf16 = zhrf16:gsub("n", "ท")
zhrf16 = zhrf16:gsub("m", "ണ")
zhrf16 = zhrf16:gsub('ض', 'ضِٰـِۢ')
zhrf16 = zhrf16:gsub('ص', 'صِٰـِۢ')
zhrf16 = zhrf16:gsub('ث', 'ثِٰـِۢ')
zhrf16 = zhrf16:gsub('ق', 'قِٰـِۢ')
zhrf16 = zhrf16:gsub('ف', 'فِٰ͒ـِۢ')
zhrf16 = zhrf16:gsub('غ', 'غِٰـِۢ')
zhrf16 = zhrf16:gsub('ع', 'عِٰـِۢ')
zhrf16 = zhrf16:gsub('خ', 'خِٰ̐ـِۢ')
zhrf16 = zhrf16:gsub('ح', 'حِٰـِۢ')
zhrf16 = zhrf16:gsub('ج', 'جِٰـِۢ')
zhrf16 = zhrf16:gsub('ش', 'شِٰـِۢ')
zhrf16 = zhrf16:gsub('س', 'سِٰـِۢ')
zhrf16 = zhrf16:gsub('ي', 'يِٰـِۢ')
zhrf16 = zhrf16:gsub('ب', 'بِٰـِۢ')
zhrf16 = zhrf16:gsub('ل', 'لِٰـِۢ')
zhrf16 = zhrf16:gsub('ا', 'ا')
zhrf16 = zhrf16:gsub('ت', 'تِٰـِۢ')
zhrf16 = zhrf16:gsub('ن', 'نِٰـِۢ')
zhrf16 = zhrf16:gsub('م', 'مِٰـِۢ')
zhrf16 = zhrf16:gsub('ك', 'ڪِٰـِۢ')
zhrf16 = zhrf16:gsub('ط', 'طِٰـِۢ')
zhrf16 = zhrf16:gsub('ظ', 'ظِٰـِۢ')
zhrf16 = zhrf16:gsub('ء', 'ء')
zhrf16 = zhrf16:gsub('ؤ', 'ؤ')
zhrf16 = zhrf16:gsub('ر', 'ر')
zhrf16 = zhrf16:gsub('ى', 'ى')
zhrf16 = zhrf16:gsub('ز', 'ز')
zhrf16 = zhrf16:gsub('و', 'ﯛ̲୭')
zhrf16 = zhrf16:gsub("ه", "ۿۿہ")

local zhrf17 = text:gsub("q", "Ꮢ")
zhrf17 = zhrf17:gsub("w", "ẁ́̀́")
zhrf17 = zhrf17:gsub("e", "ξ")
zhrf17 = zhrf17:gsub("r", "Ꮢ")
zhrf17 = zhrf17:gsub("t", "Ƭ")
zhrf17 = zhrf17:gsub("y", "ɣ")
zhrf17 = zhrf17:gsub("u", "Ꮜ")
zhrf17 = zhrf17:gsub("i", "Ĩ")
zhrf17 = zhrf17:gsub("o", "♡")
zhrf17 = zhrf17:gsub("p", "Ƥ")
zhrf17 = zhrf17:gsub("a", "ᕱ")
zhrf17 = zhrf17:gsub("s", "Ƨ")
zhrf17 = zhrf17:gsub("d", "Ɗ")
zhrf17 = zhrf17:gsub("f", "ƒ")
zhrf17 = zhrf17:gsub("g", "Ǥ")
zhrf17 = zhrf17:gsub("h", "ƕ")
zhrf17 = zhrf17:gsub("j", "ʝ")
zhrf17 = zhrf17:gsub("k", "Ƙ")
zhrf17 = zhrf17:gsub("l", "Ꮭ")
zhrf17 = zhrf17:gsub("z", "ʑ")
zhrf17 = zhrf17:gsub("x", "ﾒ")
zhrf17 = zhrf17:gsub("c", "૮")
zhrf17 = zhrf17:gsub("v", "ѵ")
zhrf17 = zhrf17:gsub("b", "β")
zhrf17 = zhrf17:gsub("n", "ท")
zhrf17 = zhrf17:gsub("m", "ണ")
zhrf17 = zhrf17:gsub('ض', 'ضَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('ص', 'صَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('ث', 'ثَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('ق', 'قَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('ف', 'فَٰ͒ـُـٰٓ')
zhrf17 = zhrf17:gsub('غ', 'غَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('ع', 'عَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('خ', 'خَٰ̐ـُـٰٓ')
zhrf17 = zhrf17:gsub('ح', 'حَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('ج', 'جَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('ش', 'شَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('س', 'سَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('ي', 'يَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('ب', 'بَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('ل', 'لَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('ا', 'ا')
zhrf17 = zhrf17:gsub('ت', 'تَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('ن', 'نَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('م', 'مَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('ك', 'ڪَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('ط', 'طَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('ظ', 'ظَٰـُـٰٓ')
zhrf17 = zhrf17:gsub('ء', 'ء')
zhrf17 = zhrf17:gsub('ؤ', 'ؤ')
zhrf17 = zhrf17:gsub('ر', 'ر')
zhrf17 = zhrf17:gsub('ى', 'ى')
zhrf17 = zhrf17:gsub('ز', 'ز')
zhrf17 = zhrf17:gsub('و', 'ﯛ̲୭')
zhrf17 = zhrf17:gsub("ه", "ۿۿہ")

local zhrf18 = text:gsub("q", "℺")
zhrf18 = zhrf18:gsub("w", "Ꮤ")
zhrf18 = zhrf18:gsub("e", "Ｅ")
zhrf18 = zhrf18:gsub("r", "Ꮢ")
zhrf18 = zhrf18:gsub("t", "Ƭ")
zhrf18 = zhrf18:gsub("y", "ɣ")
zhrf18 = zhrf18:gsub("u", "ᵿ")
zhrf18 = zhrf18:gsub("i", "Ｉ")
zhrf18 = zhrf18:gsub("o", "σ")
zhrf18 = zhrf18:gsub("p", "Ꝑ")
zhrf18 = zhrf18:gsub("a", "ᗩ")
zhrf18 = zhrf18:gsub("s", "₷")
zhrf18 = zhrf18:gsub("d", "Ɗ")
zhrf18 = zhrf18:gsub("f", "Բ")
zhrf18 = zhrf18:gsub("g", "Ｇ")
zhrf18 = zhrf18:gsub("h", "ⴼ")
zhrf18 = zhrf18:gsub("j", "Ј")
zhrf18 = zhrf18:gsub("k", "₭")
zhrf18 = zhrf18:gsub("l", "Ł")
zhrf18 = zhrf18:gsub("z", "Ꙃ")
zhrf18 = zhrf18:gsub("x", "χ")
zhrf18 = zhrf18:gsub("c", "Ｃ")
zhrf18 = zhrf18:gsub("v", "ѵ")
zhrf18 = zhrf18:gsub("b", "β")
zhrf18 = zhrf18:gsub("n", "Ŋ")
zhrf18 = zhrf18:gsub("m", "ᗰ")
zhrf18 = zhrf18:gsub('ض', 'ضِٰــ')
zhrf18 = zhrf18:gsub('ص', 'صِٰــ')
zhrf18 = zhrf18:gsub('ث', 'ثِٰــ')
zhrf18 = zhrf18:gsub('ق', 'قِٰــ')
zhrf18 = zhrf18:gsub('ف', 'فِٰ͒ــ')
zhrf18 = zhrf18:gsub('غ', 'غِٰــ')
zhrf18 = zhrf18:gsub('ع', 'عِٰــ')
zhrf18 = zhrf18:gsub('خ', 'خِٰ̐ــ')
zhrf18 = zhrf18:gsub('ح', 'حِٰــ')
zhrf18 = zhrf18:gsub('ج', 'جِٰــ')
zhrf18 = zhrf18:gsub('ش', 'شِٰــ')
zhrf18 = zhrf18:gsub('س', 'سِٰــ')
zhrf18 = zhrf18:gsub('ي', 'يِٰــ')
zhrf18 = zhrf18:gsub('ب', 'بِٰــ')
zhrf18 = zhrf18:gsub('ل', 'لِٰــ')
zhrf18 = zhrf18:gsub('ا', 'آ')
zhrf18 = zhrf18:gsub('ت', 'تِٰــ')
zhrf18 = zhrf18:gsub('ن', 'نِٰــ')
zhrf18 = zhrf18:gsub('م', 'مِٰــ')
zhrf18 = zhrf18:gsub('ك', 'ڪِٰــ')
zhrf18 = zhrf18:gsub('ط', 'طِٰــ')
zhrf18 = zhrf18:gsub('ظ', 'ظِٰــ')
zhrf18 = zhrf18:gsub('ء', 'ء')
zhrf18 = zhrf18:gsub('ؤ', 'ؤ')
zhrf18 = zhrf18:gsub('ر', 'ر')
zhrf18 = zhrf18:gsub('ى', 'ى')
zhrf18 = zhrf18:gsub('ز', 'ز')
zhrf18 = zhrf18:gsub('و', 'ﯛ̲୭')
zhrf18 = zhrf18:gsub("ه", "໋۠هہؚ")
local RANDROM={'•💚','🍿﴿','❥˓ ','💝﴿ֆ','🐼🌿','🙊💙','-✨','〄💖‘','⚡️💊','-⁽🌷','🔥“','💜💭','','🎩','“̯🐼💗','🍷','❥̚͢₎😍','🌸‘','💭💔ۦ','💛💭ۦ','⚡️🔱ۦ','℡ᴖ̈💜','🌔☄️₎ۦ˛','💥♩','☻🔥“ٰۦ','℡̇✨🐯⇣✦','⁞♩⁽💎🌩₎⇣✿','ۦٰ‏┋❥͢˓🦁💛ۦ‏','⚡️♛ֆ₎','♛⇣🐰☄️₎✦','⁾⇣✿┊❥','₎✿💥🎃⁞“❥','😴✿⇣','❥┊⁽℡🦁🌸'}
local TEXTSHER = '\n*📮¦ اهلا بك عزيزي المستخدم\n🗃¦ اضغط على الاسم ليتم نسخه *\nٴ━━━━━━━━━━\n'
local TEXT_end = '*\nٴ━━━━━━━━━━\n📌¦ مطور البوت* ❪['..SUDOUSERNAME..']❫'
local SEND_SKRF = TEXTSHER..'*1 »* `'..zhrf1..' '..RANDROM[math.random(#RANDROM)]..'`\n*2 »* `'..zhrf2..' '..RANDROM[math.random(#RANDROM)]..'`\n*3 »* `'..zhrf3..' '..RANDROM[math.random(#RANDROM)]..'`\n*4 »* `'..zhrf4..' '..RANDROM[math.random(#RANDROM)]..'`\n*5 »* `'..zhrf5..' '..RANDROM[math.random(#RANDROM)]..'`\n*6 »* `'..zhrf6..' '..RANDROM[math.random(#RANDROM)]..'`\n*7 »* `'..zhrf7..' '..RANDROM[math.random(#RANDROM)]..'`\n*8 »* `'..zhrf8..' '..RANDROM[math.random(#RANDROM)]..'`\n*9 »* `'..zhrf9..' '..RANDROM[math.random(#RANDROM)]..'`\n*10 »* `'..zhrf10..' '..RANDROM[math.random(#RANDROM)]..'`\n*11 »* `'..zhrf11..' '..RANDROM[math.random(#RANDROM)]..'`\n*12 »* `'..zhrf12..' '..RANDROM[math.random(#RANDROM)]..'`\n*13 »* `'..zhrf13..' '..RANDROM[math.random(#RANDROM)]..'`\n*14 »* `'..zhrf14..' '..RANDROM[math.random(#RANDROM)]..'`\n*15 »* `'..zhrf15..' '..RANDROM[math.random(#RANDROM)]..'`\n*16 »* `'..zhrf16..' '..RANDROM[math.random(#RANDROM)]..'`\n*17 »* `'..zhrf17..' '..RANDROM[math.random(#RANDROM)]..'`\n*18 »* `'..zhrf18..' '..RANDROM[math.random(#RANDROM)]..'`'..TEXT_end
IRAQ_sendMsg(msg.chat_id_, msg.id_, 1, SEND_SKRF,  1, "md")
IRAQBOT:del(IRAQ_ID.."skrafa:name" .. msg.chat_id_ .. "" .. msg.sender_user_id_)     
end
end
end
end
local function zhrfa(msg)
if chat_type == 'super' then 
if MSG_TEXT[1] == 'تفعيل الزخرفه' and is_mod(msg) then   
if IRAQBOT:get(IRAQ_ID..'lock:skrfa'..msg.chat_id_)  then
taha = '*📮¦ تم تفعيل الزخرفه *\n✓' 
IRAQ_sendMsg( msg.chat_id_, msg.id_, 1, taha, 1, "md") 
IRAQBOT:del(IRAQ_ID..'lock:skrfa'..msg.chat_id_) 
else
taha = '*📮¦ بالتاكيد تم تفعيل الزخرفه  *\n✓' 
IRAQ_sendMsg( msg.chat_id_, msg.id_, 1, taha, 1, "md") 
end
return false
end
if MSG_TEXT[1] == 'تعطيل الزخرفه' and is_mod(msg) then   
if not IRAQBOT:get(IRAQ_ID..'lock:skrfa'..msg.chat_id_)  then
taha = '*📮¦ تم تعطيل الزخرفه *\n✓' 
IRAQ_sendMsg( msg.chat_id_, msg.id_, 1, taha, 1, "md") 
IRAQBOT:set(IRAQ_ID..'lock:skrfa'..msg.chat_id_,true) 
else
taha = '*📮¦ بالتاكيد تم تعطيل الزخرفه  *\n✓' 
IRAQ_sendMsg( msg.chat_id_, msg.id_, 1, taha, 1, "md") 
end
return false
end
if MSG_TEXT[1] == ("زخرفه") or MSG_TEXT[1] == ("زخرف") then
if not IRAQBOT:get(IRAQ_ID.."lock:skrfa"..msg.chat_id_) then   
IRAQBOT:setex(IRAQ_ID.."skrafa:name" .. msg.chat_id_ .. "" .. msg.sender_user_id_, 10000, true)   
local t = '*⚡¦* ارسل الاسم الذي تريد زخرفته \n*📬¦* سواء كان بالعربي او بالانكلش 🍁'   
IRAQ_sendMsg(msg.chat_id_, msg.id_, 1,t, 1, 'md') 
else
IRAQ_sendMsg(msg.chat_id_, msg.id_, 1,'*📬¦ الزخرفه معطله *', 1, 'md') 
end
return false
end



end
end

return {
CMDS = {
"^(زخرفه)$",
"^(زخرف)$",
"^(تفعيل الزخرفه)$",
"^(تعطيل الزخرفه)$",
},
IRAQ = zhrfa,
IRAQ_TEXT = GET_TEXT
}

end
end

]]
local function games(msg,MsgText)
if msg.type ~= "pv" and msg.GroupActive then

if MsgText[1] == "تفعيل" and MsgText[2] == "الالعاب" or MsgText[2] == "اللعبه" or MsgText[2] == "اللعبة" then
if not msg.Admin then return "*️✔┊ ❪ انجب حمبي انته كلك خلك عضو محد يحترمك هذا امر بس للادمنيه وبقيه المشرفين  ❫\n*" end
if not redis:get(IRAQ..'lock_geams'..msg.chat_id_) then 
return "*🙋🏻‍♂┊ مرحباً عزيزي "..msg.TheRankCmd.."\n✔┊ الالعاب بالتأكيد مفعله\n*" 
else 
redis:del(IRAQ..'lock_geams'..msg.chat_id_) 
return "*🙋🏻‍♂┊ مرحباً عزيزي "..msg.TheRankCmd.."\n✔┊ تم تفعيل الالعاب\n*" 
end 
end

if MsgText[1] == "تعطيل" and MsgText[2] == "الالعاب" or MsgText[2] == "اللعبه" or MsgText[2] == "اللعبة" then
if not msg.Admin then return "*✔┊ ❪ انجب حمبي انته كلك خلك عضو محد يحترمك هذا امر بس للادمنيه وبقيه المشرفين ❫\n*" end
if redis:get(IRAQ..'lock_geams'..msg.chat_id_) then 
return "*🙋🏼‍♂️┊ مرحباً عزيزي "..msg.TheRankCmd.." \n📡┊ الالعاب بالتأكيد معطله \n*" 
else
redis:set(IRAQ..'lock_geams'..msg.chat_id_,true)  
return "*🙋🏼‍♂️┊ مرحباً عزيزي "..msg.TheRankCmd.." \n📡┊ تم تعطيل الالعاب \n*" 
end   
end

if MsgText[1] == "اضف رسائل" and msg.reply_to_message_id_ == 0 then       
if not msg.Creator then return "📛*┊* هذا الامر يخص {المطور,المنشئ} فقط  \n🚶" end
local ID_USER = MsgText[2]
redis:set(IRAQ..'SET:ID:USER'..msg.chat_id_,ID_USER)  
redis:setex(IRAQ.."SETEX:MSG"..msg.chat_id_..""..msg.sender_user_id_,500,true)  
sendMsg(msg.chat_id_,msg.id_,'*📊┊ ارسل لي عدد الرسائل الذي تريده*')
end
if MsgText[1] == "اضف مجوهرات" and msg.reply_to_message_id_ == 0 then       
if not msg.Creator then return "📛*┊* هذا الامر يخص {المطور,المنشئ} فقط  \n🚶" end
local ID_USER = MsgText[2]
redis:set(IRAQ..'SET:ID:USER:NUM'..msg.chat_id_,ID_USER)  
redis:setex(IRAQ.."SETEX:NUM"..msg.chat_id_..""..msg.sender_user_id_,500,true)  
sendMsg(msg.chat_id_,msg.id_,'*📊┊ ارسل لي عدد المجوهرات الذي تريده*')
end
if not redis:get(IRAQ..'lock_geams'..msg.chat_id_) and msg.GroupActive then


if MsgText[1] == 'محيبس' or MsgText[1] == 'بات' then   
Num = math.random(1,6)
redis:set(IRAQ.."GAMES"..msg.chat_id_,Num) 
TEST = [[
*🙋🏻‍♂┊ اهلن عزيزي 
📮┊ اليك 6 ايدي اختر رقم لأستخراج البات م̷ـــِْن اليد التي تحمل المحيبس
🎁┊ الفائز يحصل على { 3 } من النقاط
ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
➀    ➁    ➂    ➃   ➄    ➅ 
↓   ↓   ↓    ↓   ↓   ↓ 
👊‹›👊‹›👊‹›👊‹›👊‹›👊
*
]]
sendMsg(msg.chat_id_,msg.id_,TEST)   
redis:setex(IRAQ.."SET:GAME" .. msg.chat_id_ .. "" .. msg.sender_user_id_, 100, true)  
return false  
end




if MsgText[1] == 'عكس' then
hasone = {'باي','فهمت','موزين','اسمعك','احبك','موحلو','نضيف','حاره','ناصي','جوه','سريع','ونسه','طويل','سمين','ضعيف','شريف','شجاع','رحت','عدل','نشيط','شبعان','موعطشان','خوش ولد','اني','هادئ'}
name = hasone[math.random(#hasone)]
redis:set(IRAQ..':Set_Aks:'..msg.chat_id_,name)
name = string.gsub(name,'باي','هلو')
name = string.gsub(name,'فهمت','مافهمت')
name = string.gsub(name,'موزين','زين')
name = string.gsub(name,'اسمعك','ماسمعك')
name = string.gsub(name,'احبك','ماحبك')
name = string.gsub(name,'موحلو','حلو')
name = string.gsub(name,'نضيف','وصخ')
name = string.gsub(name,'حاره','بارده')
name = string.gsub(name,'ناصي','عالي')
name = string.gsub(name,'جوه','فوك')
name = string.gsub(name,'سريع','بطيء')
name = string.gsub(name,'ونسه','ضوجه')
name = string.gsub(name,'طويل','قزم')
name = string.gsub(name,'سمين','ضعيف')
name = string.gsub(name,'ضعيف','قوي')
name = string.gsub(name,'شريف','كواد')
name = string.gsub(name,'شجاع','جبان')
name = string.gsub(name,'رحت','اجيت')
name = string.gsub(name,'عدل','ميت')
name = string.gsub(name,'نشيط','كسول')
name = string.gsub(name,'شبعان','جوعان')
name = string.gsub(name,'موعطشان','عطشان')
name = string.gsub(name,'خوش ولد','موخوش ولد')
name = string.gsub(name,'اني','انته')
name = string.gsub(name,'هادئ','عصبي')
return  '✖️┊عكس كلمه » ❴ '..name..' ❵ '
end


if (MsgText[1] == 'اسرع' or MsgText[1] == 'الاسرع') then
local NUM = math.random(10,1000)
redis:set(IRAQ..':NUM_SET:'..msg.chat_id_,(NUM * 3))
local Smiles = {'🍏','🍎','🍐',NUM,NUM,NUM,NUM,NUM,'🍊','🍋','🍌','🍉',NUM,NUM,NUM,NUM,NUM,'🍇','🍓','🍈','🍒',NUM,NUM,NUM,NUM,NUM,'??','🍍','🥥','🥝','🍅',NUM,NUM,NUM,NUM,NUM,'🍆','🥑','🥦','🥒',NUM,NUM,NUM,NUM,NUM,'🌶','🌽','🥕','🥔','🍠','🥐','🍞',NUM,NUM,NUM,NUM,NUM,'🥖','🥨','🧀','🥚','🍳','🥞','🥓',NUM,NUM,NUM,NUM,NUM,'🥩','🍗','🍖','🌭','🍔','🍟',NUM,NUM,NUM,NUM,NUM,'🍕','🥪','🥙','🍼','☕️','🍵',NUM,NUM,NUM,NUM,NUM,'🥤','🍶','🍺','🍻',NUM,NUM,NUM,NUM,NUM,'🏀','⚽️','🏈','⚾️','🎾','🏐',NUM,NUM,NUM,NUM,NUM,'🏉','🎱','🏓','🏸','🥅','🎰','🎮',NUM,NUM,NUM,NUM,NUM,'🎳','🎯','🎲','🎻','🎸','🎺','🥁','??',NUM,NUM,NUM,NUM,NUM,'🎼','🎧','🎤','🎬','🎨','🎭',NUM,NUM,NUM,NUM,NUM,'🎪','🎟','🎫','🎗','🏵','🎖','🏆','🥌','🛷','🚕','🚗','🚙','🚌',NUM,NUM,NUM,NUM,NUM,'🚎','🏎','🚓','🚑','🚚','🚛','🚜','🇮🇶','⚔','🛡','🔮','🌡','💣','📌',NUM,NUM,NUM,NUM,NUM,'📍','📓','📗','📂','📅','📪','📫','📬',NUM,NUM,NUM,NUM,NUM,'📭','⏰','📺','🎚','☎️',NUM,NUM,NUM,NUM,NUM,'📡'}
Emoji = Smiles[math.random(#Smiles)]
redis:set(IRAQ..':Set_Smile:'..msg.chat_id_,Emoji)
if tonumber(redis:get(IRAQ..':Set_Smile:'..msg.chat_id_)) == tonumber(redis:get(IRAQ..':NUM_SET:'..msg.chat_id_)) then
return '👁‍🗨┇اول من يكتب هذه العدد يفوز ؛  ››`'..(redis:get(IRAQ..':Set_Smile:'..msg.chat_id_))..'`'
else
return '️👁‍🗨┇اول من يكتب هذه السمايل يفوز ››    `'..(redis:get(IRAQ..':Set_Smile:'..msg.chat_id_))..'`'
end
end
if MsgText[1] == 'ترتيب' then
hasone = {'سحور','سياره','استقبال','قنفه','ايفون','بزونه','مطبخ','كرستيانو','دجاجه','مدرسه','الوان','غرفه','ثلاجه','كهوه','سفينه','العراق','محطه','طياره','رادار','منزل','مستشفى','كهرباء','تفاحه','اخطبوط','سلمون','فرنسا','برتقاله','تفاح','مطرقه','بتيته','لهانه','شباك','باص','سمكه','ذباب','تلفاز','حاسوب','انترنيت','ساحه','جسر'};
name = hasone[math.random(#hasone)]
redis:set(IRAQ..':Set_Arg:'..msg.chat_id_,name)
name = string.gsub(name,'سحور','س ر و ح')
name = string.gsub(name,'سياره','ه ر س ي ا')
name = string.gsub(name,'استقبال','ل ب ا ت ق س ا')
name = string.gsub(name,'قنفه','ه ق ن ف')
name = string.gsub(name,'ايفون','و ن ي ف ا')
name = string.gsub(name,'بزونه','ز و ب ه ن')
name = string.gsub(name,'مطبخ','خ ب ط م')
name = string.gsub(name,'كرستيانو','س ت ا ن و ك ر ي')
name = string.gsub(name,'دجاجه','ج ج ا د ه')
name = string.gsub(name,'مدرسه','ه م د ر س')
name = string.gsub(name,'الوان','ن ا و ا ل')
name = string.gsub(name,'غرفه','غ ه ر ف')
name = string.gsub(name,'ثلاجه','ج ه ث ل ا')
name = string.gsub(name,'كهوه','ه ك ه و')
name = string.gsub(name,'سفينه','ه ن ف ي س')
name = string.gsub(name,'العراق','ق ع ا ل ر ا')
name = string.gsub(name,'محطه','ه ط م ح')
name = string.gsub(name,'طياره','ر ا ط ي ه')
name = string.gsub(name,'رادار','ر ا ر ا د')
name = string.gsub(name,'منزل','ن ز م ل')
name = string.gsub(name,'مستشفى','ى ش س ف ت م')
name = string.gsub(name,'كهرباء','ر ب ك ه ا ء')
name = string.gsub(name,'تفاحه','ح ه ا ت ف')
name = string.gsub(name,'اخطبوط','ط ب و ا خ ط')
name = string.gsub(name,'سلمون','ن م و ل س')
name = string.gsub(name,'فرنسا','ن ف ر س ا')
name = string.gsub(name,'برتقاله','ر ت ق ب ا ه ل')
name = string.gsub(name,'تفاح','ح ف ا ت')
name = string.gsub(name,'مطرقه','ه ط م ر ق')
name = string.gsub(name,'بتيته','ب ت ت ي ه')
name = string.gsub(name,'لهانه','ه ن ا ه ل')
name = string.gsub(name,'شباك','ب ش ا ك')
name = string.gsub(name,'باص','ص ا ب')
name = string.gsub(name,'سمكه','ك س م ه')
name = string.gsub(name,'ذباب','ب ا ب ذ')
name = string.gsub(name,'تلفاز','ت ف ل ز ا')
name = string.gsub(name,'حاسوب','س ا ح و ب')
name = string.gsub(name,'انترنيت','ا ت ن ر ن ي ت')
name = string.gsub(name,'ساحه','ح ا ه س')
name = string.gsub(name,'جسر','ر ج س')
return '🛠┊اسرع واحد يرتبها ❴ * '..name..' * ❵ ' 
end
if MsgText[1] == 'معاني' then
hasone = {'قرد','دجاجه','بطريق','ضفدع','بومه','نحله','ديج','جمل','بقره','دولفين','تمساح','قرش','نمر','اخطبوط','سمكه','خفاش','اسد','فأر','ذئب','فراشه','عقرب','زرافه','قنفذ','تفاحه','باذنجان'}
name = hasone[math.random(#hasone)]
redis:set(IRAQ..':Set_Name_Meant:'..msg.chat_id_,name)
name = string.gsub(name,'قرد','🐒')
name = string.gsub(name,'دجاجه','🐔')
name = string.gsub(name,'بطريق','🐧')
name = string.gsub(name,'ضفدع','🐸')
name = string.gsub(name,'بومه','🦉')
name = string.gsub(name,'نحله','🐝')
name = string.gsub(name,'ديك','🐓')
name = string.gsub(name,'جمل','🐫')
name = string.gsub(name,'بقره','🐄')
name = string.gsub(name,'دولفين','🐬')
name = string.gsub(name,'تمساح','🐊')
name = string.gsub(name,'قرش','🦈')
name = string.gsub(name,'نمر','🐅')
name = string.gsub(name,'اخطبوط','🐙')
name = string.gsub(name,'سمكه','🐟')
name = string.gsub(name,'خفاش','🦇')
name = string.gsub(name,'اسد','🦁')
name = string.gsub(name,'فأر','🐭')
name = string.gsub(name,'ذئب','🐺')
name = string.gsub(name,'فراشه','🦋')
name = string.gsub(name,'عقرب','🦂')
name = string.gsub(name,'زرافه','🦒')
name = string.gsub(name,'قنفذ','🦔')
name = string.gsub(name,'تفاحه','🍎')
name = string.gsub(name,'باذنجان','🍆')
return '👁‍🗨┊ اول من يكتب معنى السمايل يفوز ❴ '..name..' ❵'
end

if MsgText[1] == 'مجوهراتي' then 
local points = redis:get(IRAQ..':User_Points:'..msg.chat_id_..msg.sender_user_id_)
if points and points ~= "0" then
return '*📮┊ عدد المجوهرات التي ربحتها هي » ❴ '..points..' ❵\n📬┊ تسطيع بيع مجوهراتك ولحصول على (100) رساله مقابل كل مجوهرات من المجوهرات *\n'
else
return ' *💬┊ ليس لديك مجوهرات ،\n📬┊ للحصول ؏ مجوهرات ،\n📮┊ ارسل الالعاب وابدأ اللعب ! *'
end
end
if MsgText[1] == 'بيع مجوهراتي' then
if MsgText[2] == "0" then
return '📛┊ هناك خطأ عزيزي  \n🔖┊ يجب ان يكون البيع ع الاقل 1 من المجوهرات . 'end
local points = redis:get(IRAQ..':User_Points:'..msg.chat_id_..msg.sender_user_id_)
if tonumber(MsgText[2]) > tonumber(points) then
return '📛| عذرا ليس لديك مجوهرات بهذا العدد لبيعهن' 
end
if points == "0" then
return '📛 ┊ للاسف ليس لديك مجوهرات \n🔖 ┊ للحصول على مجوهرات العب احد الالعاب الموجوده في `قائمه الالعاب`'
else
local Total_Point = MsgText[2] * 100
redis:decrby(IRAQ..':User_Points:'..msg.chat_id_..msg.sender_user_id_,MsgText[2])  
redis:incrby(IRAQ..'msgs:'..msg.sender_user_id_..':'..msg.chat_id_,Total_Point)  
return "💰┊ تم خصم {* "..MsgText[2].." *} من مجوهراتك\n📮| تم زياده {* "..Total_Point.."* } من الرسائل \n📑| اصبحت رسائلك { *"..redis:get(max..'msgs:'..msg.sender_user_id_..':'..msg.chat_id_).."* } رساله\n🔖"
end
end
if MsgText[1] == "الالعاب" or MsgText[1] == "اللعبه" or MsgText[1] == "اللعبة" then
return [[ 
🙋🏻‍♂┊ اهلا بك عزيزي 
🎮┊ اليك الالعاب ک تالي ...
🚸 ≈ الاسرع » تطابق السمايلات
📬 ≈ معاني » لعبه معاني السمايلات
🎭 ≈ ترتيب » لعبه ترتيب الكلمات
🎮 ≈ روليت » لعبه روليت الشهيره 
📛 ≈ عكس » لعبه عكس الكلمات  
💥 ≈ محيبس » لعبه المحيبس او بات 
ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
]]
end
if MsgText[1] == 'روليت' then
redis:del(IRAQ..":Number_Add:"..msg.chat_id_..msg.sender_user_id_) 
redis:del(IRAQ..':List_Rolet:'..msg.chat_id_)  
redis:setex(IRAQ..":Start_Rolet:"..msg.chat_id_..msg.sender_user_id_,3600,true)  
return '*🎪┊ حسننا لنلعب ,ارسل عدد الاعبين للروليت\n*'
end
if MsgText[1] == 'نعم' and redis:get(IRAQ..":Witting_StartGame:"..msg.chat_id_..msg.sender_user_id_) then
local list = redis:smembers(IRAQ..':List_Rolet:'..msg.chat_id_) 
if #list == 1 then 
return "📛| لم يكتمل العدد الكلي للاعبين .!؟" 
elseif #list == 0 then 
return "📛| عذرا لم تقوم باضافه اي لاعب .؟!" 
end 
local UserName = list[math.random(#list)]
GetUserName(UserName,function(arg,data)
redis:incrby(IRAQ..':User_Points:'..msg.chat_id_..data.id_,2)
end,nil)
redis:del(IRAQ..':List_Rolet:'..msg.chat_id_) 
redis:del(IRAQ..":Witting_StartGame:"..msg.chat_id_..msg.sender_user_id_)
return '✔┊ تم اختيار الشخص الاتي \n🌟┊ صاحب الحظ ( ['..UserName..'] ) \n💰┊  ربحت معنا²مجوهرات \n' 
end
if MsgText[1] == 'الاعبين' then
local list = redis:smembers(IRAQ..':List_Rolet:'..msg.chat_id_) 
local Text = '\n*ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــ*\n' 
if #list == 0 then 
return '*📮┊* لا يوجد لاعبين هنا ' 
end 
for k, v in pairs(list) do 
Text = Text..k.."•  » [" ..v.."] »\n"  
end 
return Text
end
if MsgText[1] == 'قائمه الالعاب' then
sendMsg(msg.chat_id_,msg.id_,[[
🙋🏻‍♂┊ اهلا بك عزيزي 
🎮┊ اليك الالعاب ک تالي ...
🚸 ≈ الاسرع » تطابق السمايلات
📬 ≈ معاني » لعبه معاني السمايلات
🎭 ≈ ترتيب » لعبه ترتيب الكلمات
🎮 ≈ روليت » لعبه روليت الشهيره 
📛 ≈ عكس » لعبه عكس الكلمات  
💥 ≈ محيبس » لعبه المحيبس او بات 
ـــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
⚖┊ ݪݪـﻤزيد م̷ـــن آݪمعـݪومـآت ݛآسݪنآ
⚖┊ مطور آݪـبوت ↓
⚖┊ م •⊱ ]]..SUDO_USER..[[ ⊰• √]])
end
end
end
end
local function procces(msg)
if msg.text and not redis:get(IRAQ..'lock_geams'..msg.chat_id_) then
if msg.text == redis:get(IRAQ..':Set_Smile:'..msg.chat_id_) then --//  الاسرع
redis:incrby(IRAQ..':User_Points:'..msg.chat_id_..msg.sender_user_id_,1)  
redis:del(IRAQ..':Set_Smile:'..msg.chat_id_)
return sendMsg(msg.chat_id_,msg.id_,'*\n🎊┊ احسنت اجابتك صحيحه*')end

if msg.text == redis:get(IRAQ..':Set_Aks:'..msg.chat_id_) then -- // عكس
redis:incrby(IRAQ..':User_Points:'..msg.chat_id_..msg.sender_user_id_,1)  
redis:del(IRAQ..':Set_Aks:'..msg.chat_id_)
return sendMsg(msg.chat_id_,msg.id_,'*\n🎊┊ احسنت اجابتك صحيحه*')end

if msg.text == redis:get(IRAQ..':Set_Arg:'..msg.chat_id_) then -- // الترتيب
redis:incrby(IRAQ..':User_Points:'..msg.chat_id_..msg.sender_user_id_,1)  
redis:del(IRAQ..':Set_Arg:'..msg.chat_id_)
return sendMsg(msg.chat_id_,msg.id_,'*\n🎊┊ احسنت اجابتك صحيحه*')end
if msg.text == redis:get(IRAQ..':Set_Name_Meant:'..msg.chat_id_) then --// المعاني
redis:incrby(IRAQ..':User_Points:'..msg.chat_id_..msg.sender_user_id_,1)  
redis:del(IRAQ..':Set_Name_Meant:'..msg.chat_id_)
return sendMsg(msg.chat_id_,msg.id_,'*\n🎊┊ احسنت اجابتك صحيحه*')end
if redis:get(IRAQ.."SETEX:MSG"..msg.chat_id_..""..msg.sender_user_id_) then 
if msg.text:match("^(%d+)$") then
if tonumber(msg.text:match("^(%d+)$")) > 99999999 then
sendMsg(msg.chat_id_,msg.id_,"*📬┊ لا تستطيع اضافة اكثر من 99999999 رساله\n*")   
redis:del(IRAQ.."SETEX:MSG"..msg.chat_id_..""..msg.sender_user_id_)  
return false  end 
local GET_IDUSER = redis:get(IRAQ..'SET:ID:USER'..msg.chat_id_)  
sendMsg(msg.chat_id_,msg.id_,"\n📬*┊ روح خالي 😉 تم اضافة له { "..msg.text.." }* رساله")
redis:incrby(IRAQ..'msgs:'..GET_IDUSER..':'..msg.chat_id_,msg.text)  
end
redis:del(IRAQ.."SETEX:MSG"..msg.chat_id_..""..msg.sender_user_id_)  
end

if redis:get(IRAQ.."SETEX:NUM"..msg.chat_id_..""..msg.sender_user_id_) then 
if msg.text:match("^(%d+)$") then
if tonumber(msg.text:match("^(%d+)$")) > 99999999 then
sendMsg(msg.chat_id_,msg.id_,"*📬┊ لا تستطيع اضافة اكثر من 99999999 نقطه\n*")   
redis:del(IRAQ.."SETEX:MSG"..msg.chat_id_..""..msg.sender_user_id_)  
return false  end 
local GET_IDUSER = redis:get(IRAQ..'SET:ID:USER:NUM'..msg.chat_id_)  
sendMsg(msg.chat_id_,msg.id_,"\n📬*┊ طكو طكو عمي 😻 تم اضافة له { "..msg.text.." }* مجوهره")
redis:incrby(IRAQ..':User_Points:'..msg.chat_id_..GET_IDUSER,msg.text)  
end
redis:del(IRAQ.."SETEX:MSG"..msg.chat_id_..""..msg.sender_user_id_)  
end


if msg.text:match("^(%d+)$") and redis:get(IRAQ..":Start_Rolet:"..msg.chat_id_..msg.sender_user_id_) then  --// استقبال اللعبه الدمبله
if msg.text == "1" then
Text = "*📮┊* لا استطيع بدء اللعبه بلاعب واحد فقط\n"
else
redis:set(IRAQ..":Number_Add:"..msg.chat_id_..msg.sender_user_id_,msg.text)  
Text = '\n💬┊ تم بدء تسجيل السته\n💱┊ يرجى ارسال المعرفات \n🎊┊ الفائز يحصل على 2 مجوهرات\n🎯┊ عدد الاعبين المطلوب ❪ *'..msg.text..'* ❫\n'
end
redis:del(IRAQ..":Start_Rolet:"..msg.chat_id_..msg.sender_user_id_)  
return sendMsg(msg.chat_id_,msg.id_,Text)    
end
if msg.text:match('^(@[%a%d_]+)$') and redis:get(IRAQ..":Number_Add:"..msg.chat_id_..msg.sender_user_id_) then    --// استقبال الاسماء
if redis:sismember(IRAQ..':List_Rolet:'..msg.chat_id_,msg.text) then
return sendMsg(msg.chat_id_,msg.id_,'*📮┊* المعرف {['..msg.text..']} موجود اساسا' )
end
redis:sadd(IRAQ..':List_Rolet:'..msg.chat_id_,msg.text)
local CountAdd = redis:get(IRAQ..":Number_Add:"..msg.chat_id_..msg.sender_user_id_)
local CountAll = redis:scard(IRAQ..':List_Rolet:'..msg.chat_id_)
local CountUser = CountAdd - CountAll
if tonumber(CountAll) == tonumber(CountAdd) then 
redis:del(IRAQ..":Number_Add:"..msg.chat_id_..msg.sender_user_id_) 
redis:setex(IRAQ..":Witting_StartGame:"..msg.chat_id_..msg.sender_user_id_,1400,true)  
return sendMsg(msg.chat_id_,msg.id_,"📮┊ تم ادخال المعرف  ❪ ["..msg.text.."] ❫\n🔖┊ تم اكمال العدد الكلي\n📛┊ هل انت مستعد  رسل (نعم) للبدء \n")
end 
return sendMsg(msg.chat_id_,msg.id_,"📮┊ تم ادخال المعرف ❪ ["..msg.text.."] ❫\n🔖┊ تبقى *{ "..CountUser.." }* لاعبين ليكتمل العدد\n📑┊ ارسل المعرف التالي\n")
end
end 


if redis:get(IRAQ.."SET:GAME" .. msg.chat_id_ .. "" .. msg.sender_user_id_) then  
if msg.text:match("^(%d+)$") then
local NUM = msg.text:match("^(%d+)$")
if tonumber(NUM) > 6 then
sendMsg(msg.chat_id_,msg.id_,"*📬┊ عذرا لا يوجد سواء { 6 } اختيارات فقط ارسل اختيارك مره اخره*\n")   
return false  end 
local GETNUM = redis:get(IRAQ.."GAMES"..msg.chat_id_)
if tonumber(NUM) == tonumber(GETNUM) then
redis:del(IRAQ.."SET:GAME" .. msg.chat_id_ .. "" .. msg.sender_user_id_)   
sendMsg(msg.chat_id_,msg.id_,'*✔┊ العب وخوش تلعب \n✔┊ حصلت على 3 مجوهرات \n*')   
redis:incrby(IRAQ..':User_Points:'..msg.chat_id_..msg.sender_user_id_,3)  
elseif tonumber(NUM) ~= tonumber(GETNUM) then
redis:del(IRAQ.."SET:GAME" .. msg.chat_id_ .. "" .. msg.sender_user_id_)   
sendMsg(msg.chat_id_,msg.id_,'*📮┊ للاسف لقد خسرت \n📬┊ المحبس بيد رقم ❪ '..GETNUM..' ❫\n💥┊ حاول مره اخرى للعثور على المحيبس\n*')   
end
end
end
if msg.text then  
tdcli_function ({ID = "GetUser",user_id_ = msg.sender_user_id_}, function(arg,data) 
if redis:get(IRAQ.."chencher"..msg.sender_user_id_) then 
if redis:get(IRAQ.."chencher"..msg.sender_user_id_) ~= data.first_name_ then 
hasan = '['..(redis:get(IRAQ.."chencher"..msg.sender_user_id_) or '')..']'
hasam = '['..data.first_name_..']'
local hasa ={ 
'\n شكو غيرت اسمك  يا حلو 😹🌚',
'\n شهل اسم الفيطي  '..hasam.. ' \n رجعه ؏ قديم \n '..hasan..'',
'\n  ها ها شو غيرت اسمك 🤔😹',
'\n شكو غيرت اسمك شنو قطيت وحده جديده 😹😹🌚',
'\n شو غيرت اسمك شنو تعاركت ويه الحب ؟😹🌞',
'\n ها ولك مو جان  اسمك   '..hasan..' شكو غيرته ',
'\n شكو غيرت اسمك شسالفه ؟؟ 🤔🌞'
}
sendMsg(msg.chat_id_,msg.id_,hasa[math.random(#hasa)])
end  
end
redis:set(IRAQ.."chencher"..msg.sender_user_id_, data.first_name_) 
end,nil) 
end



end
return {
IRAQ = {
"^(نعم)$", 
"^(الاعبين)$",  
"^(الالعاب)$", 
"^(محيبس)$", 
"^(عكس)$", 
"^(بات)$", 
'^(تعطيل) (.+)$',
'^(تفعيل) (.+)$',
"^(اسرع)$",
"^(الاسرع)$",
"^(مجوهراتي)$",
"^(ترتيب)$", 
"^(معاني)$", 
"^(اضف رسائل) (%d+)$",
"^(اضف مجوهرات) (%d+)$",
"^(بيع مجوهراتي) (%d+)$",
"^(روليت)$", 
"^(قائمه الالعاب)$", 
 },
end
end

return {
CMDS = {
"^(العاب)$",
"^(الالعاب)$",
"^(تفعيل الالعاب)$",
"^(تعطيل الالعاب)$",
},
IRAQ = games,
IRAQ_TEXT = GET_TEXT
